<html>
<head>
  <%@include file="header.phtml"%>
   <title><%syspref var="site.name" %> :: admin :: pluginlist</title>
</head>
<body>
<%@include file="tagline.phtml"%>
   <div id="page-wrapper">
    <div id="page-content">
 
<div class="snip-buttons"> </div> 

<div class="flash-message"><%flash var="msg"%></div>
   <div class="snip-wrapper">
      <div class="snip-content">

          <h3>Plugin List</h3>
        
        <table>
            <tr><td><b>Plugin Name</b></td><td><b>Enabled</b></td><td> &nbsp; </td></tr>
          <% foreach var="plugins" val="plugin"%>
        <tr>
            <td><%$plugin.name%></td>
            <td><a href="toggle_enabled?plugin=<%$plugin.name%>"><%boolean var="plugin.enabled"%></a></td>
			<td><a href="edit_prefs?plugin=<%$plugin.name%>">Prefs &gt;&gt;</a></td>
        </tr>
        <tr>
            <td colspan="3"><i><%$plugin.description%></i> &nbsp; </td>
        </tr>
          <% end %>
        </table>
          
     </div>
      </div>
      </div>
      </div>
         
</div>

<div id="page-bottom"><a href="/space/contact+info">contact info</a> | Copyright 1995-2005 Bill 
Welliver</div>
</body>
</html>

