<div class="flash-message"><%flash %></div>
<div style="text-align: left">
    <h3>My Account</h3>    
    <ul>
        <li><%action_link action="edit"%><%LOCALE id="" string="Manage My Account"%></a>
    </ul>
    <ul>
        <li><%action_link action="listwip"%><%LOCALE id="111" string="Work with WIP items"%></a>
    </ul>
    <ul>
        <li><%action_link action="prefs"%><%LOCALE id="113" string="Preferences"%></a>
    </ul>
</div>
