<%@include file="top.phtml"%>
<%@include file="adminheader.phtml"%>
   <title><%syspref var="site.name" %> :: my account :: <%LOCALE id="132" string="edit user"%></title>
   <link rel="STYLESHEET" type="text/css" href="<%syspref var="site.url"%>/static/javascripts/fins_release/widget/templates/ComboPicker.css"/>
<%@include file="adminpagebegin.phtml"%>
<div class="flash-message"><%flash %></div>

          <h3><%LOCALE id="133" string="Account Settings"%></h3>

	<form action="" method="post">


<table width="75%"> 
<tr>
<td>
        <b><%LOCALE id="66" string="Username"%>:</b> 
</td>
<td>
<%$user.username%>
        <br />
</td>
</tr>
<tr>
<td>
        <b><%LOCALE id="134" string="Real Name"%>:</b>
</td>
<td>
 <input type="text" size="32" name="name" value="<%$user.name%>" />
        <br />
</td>
</tr>
<tr>
<td>
        <b><%LOCALE id="68" string="Email"%>:</b>
</td>
<td>
 <input type="text" size="32" name="email" value="<%$user.email%>" />
        <p/>
</td>
</tr>

<tr>
<td colspan="2">
<div dojoType="dijit.TitlePane" title="Change Password" open="false" id="passwordpane">
<table>
<tr>
<td>
        <b><%LOCALE id="17" string="Password"%>:</b> 
</td>
<td>
<input type="password" size="32" name="password" value="" />
        <br />
</td>
</tr>
<tr>
<td>
        <b><%LOCALE id="67" string="Confirm Password"%>:</b>
</td>
<td>
 <input type="password" size="32" name="confirmpassword" value="" />
</td>
</tr>
</table>
</div>
</td>
</tr>

<tr>
<td colspan="2">
	<div dojoType="dijit.TitlePane" title="Group Membership" open="true" id="grouppane">
<%foreach var="$user.groups" val="group"%>
<li><%$group.name%>
<%end%>
</div>
</td>
</tr>

<tr>
<td colspan="2">
        <p/>



        <button name="action" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
        <button name="action" value="Save"><%LOCALE id="127" string="Save"%></button>
</td>
</tr>
</table>

<%@include file="pageend.phtml"%>
<%@include file="adminfooter.phtml"%>

<script type="text/javascript">
  dojo.require("dijit.form.Button");
  dojo.require("dijit.TitlePane");
</script>


<%@include file="bottom.phtml"%>

