<div class="flash-message"><%flash %></div>
<div style="text-align: left">
    <h3>Admin</h3>    
	<ul>
		<li><%action_link action="listusers"%><%LOCALE id="108" string="Work with Users"%></a>
		<li><%action_link action="listgroups"%><%LOCALE id="109" string="Work with Groups"%></a>
		<li><%action_link action="listacls"%><%LOCALE id="110" string="Work with ACLs"%></a>
	</ul>
    <ul>
        <li><%action_link action="listwip"%><%LOCALE id="111" string="Work with WIP items"%></a>
    </ul>
    <ul>
        <li><%action_link action="plugin"%><%LOCALE id="112" string="Plugins"%></a>
        <li><%action_link action="prefs"%><%LOCALE id="113" string="Preferences"%></a>
        <li><%action_link action="themes"%><%LOCALE id="114" string="Manage Themes"%></a>
    </ul>
	<ul>
		<li><%action_link action="shutdown"%><%LOCALE id="115" string="Shutdown"%></a>
	</ul>
</div>
