<html>
<head>
  <%@include file="header.psp" %>
   <title><%config.site.name%> :: admin</title>
</head>
<body>
<%@include file="tagline.psp" %>
   <div id="page-wrapper">
    <div id="page-content">
<div class="snip-buttons">  </div> 

<div class="flash-message"><%flash var="msg"%></div>
   <div class="snip-wrapper">
      <div class="snip-content">

          <h3>Admin</h3>
        
	<ul>
		<li><a href="listusers">Edit Users</a>
	</ul>
          
     </div>
      </div>
      </div>
      </div>
         
</div>

<div id="page-bottom"><a href="/space/contact+info">contact info</a> | Copyright 1995-2005 Bill 
Welliver</div>
</body>
</html>
