  <%@include file="top.phtml" %>
   <title><%syspref var="site.name" %> :: admin</title>
  <%@include file="header.phtml" %>
  <%@include file="pagebegin.phtml" %>

<div class="flash-message"><%flash var="msg"%></div>
          <h3>Admin</h3>
        
	<ul>
		<li><a href="listusers">Work with Users</a>
		<li><a href="listgroups">Work with Groups</a>
		<li><a href="listacls">Work with ACLs</a>
	</ul>
        <ul>
                <li><a href="listwip">Work with WIP items</a>
        </ul>
        <ul>
                <li><a href="plugin">Plugins</a>
                <li><a href="prefs">Preferences</a>
        </ul>
	<ul>
		<li><a href="shutdown">Shutdown</a>
	</ul>
			
          
  <%@include file="footer.phtml" %>
  <%@include file="bottom.phtml" %>

