  <%@include file="top.phtml" %>
  <%@include file="adminheader.phtml" %>
   <title><%syspref var="site.name" %> :: admin</title>
  
  <%@include file="adminpagebegin.phtml" %>

<div class="flash-message"><%flash %></div>
          <h3>Admin</h3>
        
	<ul>
		<li><a href="listusers"><%LOCALE id="108" string="Work with Users"%></a>
		<li><a href="listgroups"><%LOCALE id="109" string="Work with Groups"%></a>
		<li><a href="listacls"><%LOCALE id="110" string="Work with ACLs"%></a>
	</ul>
        <ul>
                <li><a href="listwip"><%LOCALE id="111" string="Work with WIP items"%></a>
        </ul>
        <ul>
                <li><a href="plugin"><%LOCALE id="112" string="Plugins"%></a>
                <li><a href="prefs"><%LOCALE id="113" string="Preferences"%></a>
                <li><a href="themes"><%LOCALE id="114" string="Manage Themes"%></a>
        </ul>
	<ul>
		<li><a href="shutdown"><%LOCALE id="115" string="Shutdown"%></a>
	</ul>
			
          
  <%@include file="adminfooter.phtml" %>
  <%@include file="bottom.phtml" %>

