  <%@include file="top.phtml"%>
  <%@include file="adminheader.phtml"%>
   <title><%syspref var="site.name" %> :: admin :: delete user</title>

<%@include file="pagebegin.phtml"%>
<div class="flash-message"><%flash %></div>

          <h3>Edit User</h3>

	<form action="" method="post">
        
The user <%$user.Name%> owns the the following objects, or versions of the 
following 
documents:
<p>
<% if sizeof(data["user"]["objects"]) || sizeof(data["user"]["object_versions"]) %>
<div style="height:200px; overflow:auto;">
  <% foreach var="$user.objects" val="objs" %>
    <li> <%$objs.path%>
  <% end %>
</div>
<p>
Please choose the user to which these objects will be reassigned:
<p>
<select size="10" name="reassign_to">
<%foreach var="$all_users" val="u" %>
<option value="<%$u.id%>"><%$u.Name%> [<%$u.UserName%>]
<% end %>
</select>

<% else %>
   No objects.
<% endif %>
<p>
<!--
  <input type="hidden" name="userid" value="<%$user.id%>"/>
-->
        <button name="action" value="Cancel">Cancel</button>
        <button name="action" value="Really Delete">Really Delete</button>
</td>
</tr>
</table>
        </form>
        
<%@include file="footer.phtml"%>
<%@include file="bottom.phtml"%>

