  <%@include file="top.phtml"%>
  <%@include file="adminheader.phtml"%>
   <title><%syspref var="site.name" %> :: admin :: confirm shutdown</title>
<%@include file="adminpagebegin.phtml"%>

<div class="flash-message"><%flash %></div>

          <h3>Confirm Shutdown</h3>
        

		Do you really what to shut down this application?
		<p>
			<table>
				<tr><td>
			<form method="post">
				<input name="really_shutdown" value="Yes" type="submit"/>
				</form>
				</td><td>
				<form method="post" value="/admin/">
				<input name="cancel" value="No" type="submit"/>
			</form>
			</td></tr>
			</table>
				
<%@include file="adminpageend.phtml" %>
  <%@include file="adminfooter.phtml"%>
<%@include file="bottom.phtml"%>


