  <%@include file="top.phtml"%>
  <%@include file="adminheader.phtml"%>
   <title><%syspref var="site.name" %> :: admin :: <%LOCALE id="116" string="delete user"%></title>

<%@include file="adminpagebegin.phtml"%>
<div class="flash-message"><%flash %></div>

          <h3><%LOCALE id="117" string="Delete User"%></h3>

	<form action="" method="post">
        
<%LOCALE id="118" string="The user"%> <%$user.name%> <%LOCALE id="119" string="owns the the following objects, or versions of the following documents"%>:
<p>
<%LOCALE id="" string="Objects:"%><%sizeof var="$user.objects"%><br>
<%LOCALE id="" string="Versions:"%><%sizeof var="$user.versions"%><p>
<% if sizeof(data["user"]["objects"]) || sizeof(data["user"]["versions"]) %>
<div style="height:200px; overflow:auto;">
  <% foreach var="$user.objects" val="objs" %>
    <li> <%$objs.path%>
  <% end %>
</div>
<p>
<%LOCALE id="120" string="Please choose the user to which these objects will be reassigned"%>:
<p>
<select size="10" name="reassign_to">
<%foreach var="$all_users" val="u" %>
<option value="<%$u.id%>"><%$u.name%> [<%$u.username%>]
<% end %>
</select>

<% else %>
  <%LOCALE id="121" string="No objects."%>
<% endif %>
<p>
<!--
  <input type="hidden" name="userid" value="<%$user.id%>"/>
-->
        <button name="action" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
        <button name="action" value="Really Delete"><%LOCALE id="123" string="Really Delete"%></button>
</td>
</tr>
</table>
        </form>
        
<%@include file="adminfooter.phtml"%>
<%@include file="bottom.phtml"%>

