<html>
<head>
  <%@include file="header.phtml"%>
   <title><%syspref var="site.name" %> :: admin :: edit user</title>

<script type="text/javascript">
dojo.require("fins.widget.ComboPicker");
</script>

<script type="text/javascript">
function getMembers()
{
  var res = null;

<% if data["newgroup"] %>
    return [];
<% endif %>

  var bindArgs = {
    url:         "/admin/getgroups_json/" +  "<%$user.id%>" ,
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJson(data.toString());
        res = res.data;
    }
};

// dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
}

function getAvailable()
{
  var res = null;

  var bindArgs = {
    url:         "/admin/getgroups_json",
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJson(data.toString());
        res = res.data;
    }
};

    // dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
};
</script>

<script type="text/javascript">
        dojo.require("dojo.widget.Button2");
	dojo.require("dojo.widget.html.Button2");

   function enable_chpass()
   {
     var w = dojo.widget.manager.byId('chpass');

     if(w)
     {
       w.hide();
     }

     var p = dojo.widget.manager.byId('passwordpane');
     
     if(p)
       p.show();     
   }

   </script>
</head>
<body>
<%@include file="tagline.phtml"%>
   <div id="page-wrapper">
    <div id="page-content">
 
<div class="snip-buttons"> </div> 

<div class="flash-message"><%flash %></div>
   <div class="snip-wrapper">
      <div class="snip-content">

          <h3>Edit User</h3>

	<form action="" method="post">


<table width="75%"> 
<tr>
<td>
        <b>Username:</b> 
</td>
<td>
<%$user.UserName%>
        <br />
</td>
</tr>
<tr>
<td>
        <b>Real Name:</b>
</td>
<td>
 <input type="text" size="32" name="Name" value="<%$user.Name%>" />
        <br />
</td>
</tr>
<tr>
<td>
        <b>Email:</b>
</td>
<td>
 <input type="text" size="32" name="Email" value="<%$user.Email%>" />
        <p/>
</td>
</tr>

<tr>
<td>
        <b>Is Active?</b>
</td>
<td>
 <input type="radio" name="is_active" value="0"
 <% if !data["user"]["is_active"] %>
   checked="1"
 <% endif %>
/> No
 <input type="radio" name="is_active" value="1"
 <% if data["user"]["is_active"] %>
   checked="1"
 <% endif %>
/> Yes
        <p/>
</td>
</tr>

<tr>
<td>
        <b>Is Admin?</b>
</td>
<td>
 <input type="radio" name="is_admin" value="0"
 <% if !data["user"]["is_admin"] %>
   checked="1"
 <% endif %>
/> No
 <input type="radio" name="is_admin" value="1"
 <% if data["user"]["is_admin"] %>
   checked="1"
 <% endif %>
/> Yes
        <p/>
</td>
</tr>

<tr>
<td colspan="2">
<button dojoType="button2" widgetId="chpass" onclick="enable_chpass();">
  Change Password...
</button>
<div dojoType="Container" id="passwordpane" style="display:none;">
<table>
<tr>
<td>
        <b>Password:</b> 
</td>
<td>
<input type="password" size="32" name="Password" value="" />
        <br />
</td>
</tr>
<tr>
<td>
        <b>Confirm Password:</b>
</td>
<td>
 <input type="password" size="32" name="ConfirmPassword" value="" />
</td>
</tr>
</table>
</div>
</td>
</tr>

<tr>
<td colspan="2">
		<div dojoType="ComboPicker" loadAvailableFunction="getAvailable" loadMembersFunction="getMembers" addsId="added" removesID="removed"></div>
</td>
</tr>

<tr>
<td colspan="2">
        <p/>

        <input type="hidden" name="added" id="added"/>
        <input type="hidden" name="removed" id="removed"/>


        <button name="action" value="Cancel">Cancel</button>
        <button name="action" value="Save">Save</button>
</td>
</tr>
</table>
        </form>
        
          
     </div>
      </div>
      </div>
      </div>
         
</div>

<div id="page-bottom"><a href="/space/contact+info">contact info</a> | Powered by <a
href="http://hww3.riverweb.com/space/pike/FinScribe">FinScribe</a></div>
</body>
</html>


