  <%@include file="top.phtml" %>
  <%@include file="adminheader.phtml" %>
  <link rel="STYLESHEET" type="text/css" href="<%syspref var="site.url"%>/static/javascripts/fins_release/widget/templates/ACLBuilder.css"/>

   <title><%syspref var="site.name" %> :: admin</title>
  

  <%@include file="adminpagebegin.phtml" %>

<div class="flash-message"><%flash %></div>
<% if data["newacl"] %>
          <h3><%LOCALE id="124" string="New ACL"%></h3>
<% else %>
          <h3><%LOCALE id="125" string="Edit ACL"%></h3>
<% endif %>
	<form id="form" action="" method="post">
        <b><%LOCALE id="126" string="ACL Name"%>:</b> <input type="text" size="32" name="name" value="<%$acl.name%>" />
        <p/>
<% if data["newacl"] %>
        <input type="hidden" name="newacl" value="1"/>
<% endif %>

<script type="text/javascript">
function getUsers()
{
  var res = null;
<% if data["newacl"] %>
    return [];
<% endif %>
  var bindArgs = {
    url:         "/admin/getusers_json/",
    handleAs:   "json",
    sync: true,
    error:      function(type, errObj){
		alert("error");
    },
    load:      function(data, evt){
        // handle successful response here
       res = data.data;
    }
};

// dispatch the request
    var requestObj = dojo.xhrGet(bindArgs);

    return res;
}

function getRules()
{
  var res = null;

<% if data["newacl"] %>
    return [];
<% endif %>

  var bindArgs = {
    url:         "/admin/getrules_json/<%$acl.id %>",
    handleAs:   "json",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(data, evt){
       // handle successful response here
       res = data.data;
    }
};

// dispatch the request
var requestObj = dojo.xhrGet(bindArgs);

    return res;
}

function getGroups()
{
  var res = null;

<% if data["newacl"] %>
    return [];
<% endif %>

  var bindArgs = {
    url:         "/admin/getgroups_json/",
    handleAs:   "json",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(data, evt){
        // handle successful response here
        res = data.data;
    }
};

// dispatch the request
var requestObj = dojo.xhrGet(bindArgs);

    return res;
}
</script>

		<input type="hidden" name="rules" dojoType="fins.widget.ACLBuilder" loadAvailablerulesFunction="getRules" loadAvailableUsersFunction="getUsers" 
                        loadAvailableGroupsFunction="getGroups"/>
		<input type="hidden" name="rules2"/>

        <p/>
        <button type="submit" name="action" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
        <button type="submit" name="action" value="Save"><%LOCALE id="127" string="Save"%></button>
        </form>
        
  <%@include file="adminpageend.phtml" %>
  <%@include file="adminfooter.phtml" %>

<script type="text/javascript">
dojo.require("dijit.form.Button");
dojo.require("fins.widget.ACLBuilder");
// dojo.addOnLoad(function(){dojo.widget.createWidget(document.getElementById("form"));});
</script>

  <%@include file="bottom.phtml" %>
