<html>
<head>
  <%@include file="header.phtml"%>
 <script src="/static/javascripts/menulayer.js"></script>
<
   <title><%syspref var="site.name"%> :: admin :: edit group</title>
</head>
<body>
<%@include file="tagline.phtml"%>
   <div id="page-wrapper">
    <div id="page-content">
 
<div class="snip-buttons"> </div> 

<div class="flash-message"><%flash var="msg"%></div>
   <div class="snip-wrapper">
      <div class="snip-content">

          <h3>Edit Group</h3>

	<form action="" method="post">
        <b>Group Name:</b> <input type="text" size="32" name="Name" value="<%$group.Name%>" />
        <p/>
        <input type="hidden" name="added" id="added"/>
        <input type="hidden" name="removed" id="removed"/>

<script type="text/javascript">
function getMembers()
{
  var res = null;

  var bindArgs = {
    url:         "/admin/getusers_json/" +  "<%$group.id%>" ,
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJSON(data.toString());
        res = res.data;
    }
};

// dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
}

function getAvailable()
{
  var res = null;

  var bindArgs = {
    url:         "/admin/getusers_json/",
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJSON(data.toString());
        res = res.data;
    }
};

    // dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
};
</script>

		<div dojoType="ComboPicker" loadAvailableFunction="getAvailable" loadMembersFunction="getMembers" addsId="added" removesID="removed"></div>

<!--
        <b>User Members</b><br/>
        <% foreach var="group.users" val="member" %>
        <%$member.Name%><br />
        <% end %>

        <p/>
        <b>Group Members</b><br/>

        <% foreach var="group.groups" val="member" %>
        <%$member.Name%><br />
        <% end %>
-->
        <p/>
        <input type="submit" name="action" value="Cancel" />
        <input type="submit" name="action" value="Save" />
        </form>
        
          
     </div>
      </div>
      </div>
      </div>
         
</div>

<div id="page-bottom"><a href="/space/contact+info">contact info</a> | Copyright 1995-2005 Bill 
Welliver</div>
</body>
</html>

