  <%@ include file="top.phtml" %>
  <%@ include file="adminheader.phtml" %>

   <title><%syspref var="site.name"%> :: admin :: <%LOCALE id="128" string="edit group"%></title>

<%@include file="adminpagebegin.phtml"%>
<div class="flash-message"><%flash %></div>

<% if data["newgroup"] %>
          <h3><%LOCALE id="129" string="New Group"%></h3>
<% else %>
          <h3><%LOCALE id="130" string="Edit Group"%></h3>
<% endif %>
	<form action="" method="post">
        <b><%LOCALE id="131" string="Group Name"%>:</b> <input type="text" size="32" name="Name" value="<%$group.Name%>" />
        <p/>
        <input type="hidden" name="added" id="added"/>
        <input type="hidden" name="removed" id="removed"/>
<% if data["newgroup"] %>
        <input type="hidden" name="newgroup" value="1"/>
<% endif %>

		<div dojoType="ComboPicker" loadAvailableFunction="getAvailable" loadMembersFunction="getMembers" addsId="added" 
removesID="removed"></div>

<!--
        <p/>
        <b><%LOCALE string="Group Members"%></b><br/>

        <% foreach var="$group.groups" val="member" %>
        <%$member.Name%><br />
        <% end %>
-->
        <p/>
        <button type="submit" name="action" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
        <button type="submit" name="action" value="Save"><%LOCALE id="127" string="Save"%></button>
        </form>
        
<%@include file="adminfooter.phtml"%>

<script type="text/javascript">
function getMembers()
{
  var res = null;

<% if data["newgroup"] %>
    return [];
<% endif %>

  var bindArgs = {
    url:         "/admin/getusers_json/" +  "<%$group.id%>" ,
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJson(data.toString());
        res = res.data;
    }
};

// dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
}

function getAvailable()
{
  var res = null;

  var bindArgs = {
    url:         "/admin/getusers_json",
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJson(data.toString());
        res = res.data;
    }
};

    // dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
};
</script>

<%@include file="bottom.phtml"%>
