  <%@include file="top.phtml" %>
  <%@include file="adminheader.phtml" %>
   <title><%syspref var="site.name" %> :: admin</title>
  
<script type="text/javascript">
dojo.require("fins.widget.*");
dojo.require("dojo.json");
dojo.require("fins.widget.ACLBuilder");

 dojo.addOnLoad(function(){dojo.widget.createWidget(document.getElementById("form"));});
</script>

  <%@include file="adminpagebegin.phtml" %>

<div class="flash-message"><%flash %></div>
<% if data["newacl"] %>
          <h3><%LOCALE id="124" string="New ACL"%></h3>
<% else %>
          <h3><%LOCALE id="125" string="Edit ACL"%></h3>
<% endif %>
	<form id="form" action="" method="post">
        <b><%LOCALE id="126" string="ACL Name"%>:</b> <input type="text" size="32" name="Name" value="<%$acl.Name%>" />
        <p/>
<% if data["newacl"] %>
        <input type="hidden" name="newacl" value="1"/>
<% endif %>

<script type="text/javascript">
function getUsers()
{
  var res = null;

<% if data["newacl"] %>
    return [];
<% endif %>

  var bindArgs = {
    url:         "/admin/getusers_json/",
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJson(data.toString());
        res = res.data;
    }
};

// dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
}

function getRules()
{
  var res = null;

<% if data["newacl"] %>
    return [];
<% endif %>

  var bindArgs = {
    url:         "/admin/getrules_json/<%$acl.id %>",
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJson(data.toString());
        res = res.data;
    }
};

// dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
}

function getGroups()
{
  var res = null;

<% if data["newacl"] %>
    return [];
<% endif %>

  var bindArgs = {
    url:         "/admin/getgroups_json/",
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJson(data.toString());
        res = res.data;
    }
};

// dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
}
</script>

		<input type="hidden" name="rules" dojoType="fins:ACLBuilder" loadAvailablerulesFunction="getRules" loadAvailableUsersFunction="getUsers" 
                        loadAvailableGroupsFunction="getGroups"/>
		<input type="hidden" name="rules2"/>

        <p/>
        <button type="submit" name="action" value="Cancel"><%LOCALE id="126" string="ACL Name"%></button>
        <button type="submit" name="action" value="Save"><%LOCALE id="127" string="Save"%></button>
        </form>
        
  <%@include file="adminfooter.phtml" %>
  <%@include file="bottom.phtml" %>
