  <%@include file="top.phtml" %>
   <title><%syspref var="site.name" %> :: admin</title>
  <%@include file="header.phtml" %>
  <%@include file="pagebegin.phtml" %>

<script type="text/javascript">
dojo.require("fins.widget.*");
dojo.require("fins.widget.ACLBuilder");
</script>

<div class="flash-message"><%flash var="msg"%></div>
<% if data["newgroup"] %>
          <h3>New ACL</h3>
<% else %>
          <h3>Edit ACL</h3>
<% endif %>
	<form action="" method="post">
        <b>ACL Name:</b> <input type="text" size="32" name="Name" value="<%$acl.Name%>" />
        <p/>
        <input type="hidden" name="added" id="added"/>
        <input type="hidden" name="removed" id="removed"/>
<% if data["newgroup"] %>
        <input type="hidden" name="newacl" value="1"/>
<% endif %>

<script type="text/javascript">
function getUsers()
{
  var res = null;

<% if data["newacl"] %>
    return [];
<% endif %>

  var bindArgs = {
    url:         "/admin/getusers_json/",
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJSON(data.toString());
        res = res.data;
    }
};

// dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
}

function getRules()
{
  var res = null;

<% if data["newacl"] %>
    return [];
<% endif %>

  var bindArgs = {
    url:         "/admin/getrules_json/<%$acl.id %>",
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJSON(data.toString());
        res = res.data;
    }
};

// dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
}

function getGroups()
{
  var res = null;

<% if data["newacl"] %>
    return [];
<% endif %>

  var bindArgs = {
    url:         "/admin/getgroups_json/",
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJSON(data.toString());
        res = res.data;
    }
};

// dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
}
</script>

		<div dojoType="ACLBuilder" loadAvailablerulesFunction="getRules" loadAvailableUsersFunction="getUsers" 
                        loadAvailableGroupsFunction="getGroups" addsId="added" removesID="removed"></div>

        <p/>
        <input type="submit" name="action" value="Cancel" />
        <input type="submit" name="action" value="Save" />
        </form>
        

  <%@include file="footer.phtml" %>
  <%@include file="bottom.phtml" %>


