<%@include file="top.phtml"%>
<%@include file="adminheader.phtml"%>
   <title><%syspref var="site.name" %> :: admin :: <%LOCALE id="132" string="edit user"%></title>
<%@include file="adminpagebegin.phtml"%>
<div class="flash-message"><%flash %></div>

          <h3><%LOCALE id="133" string="Edit User"%></h3>

	<form action="" method="post">


<table width="75%"> 
<tr>
<td>
        <b><%LOCALE id="66" string="Username"%>:</b> 
</td>
<td>
<%$user.username%>
        <br />
</td>
</tr>
<tr>
<td>
        <b><%LOCALE id="134" string="Real Name"%>:</b>
</td>
<td>
 <input type="text" size="32" name="name" value="<%$user.name%>" />
        <br />
</td>
</tr>
<tr>
<td>
        <b><%LOCALE id="68" string="Email"%>:</b>
</td>
<td>
 <input type="text" size="32" name="email" value="<%$user.email%>" />
        <p/>
</td>
</tr>

<tr>
<td>
        <b><%LOCALE id="135" string="Is Active?"%></b>
</td>
<td>
 <input type="radio" name="is_active" value="0"
 <% if !data["user"]["is_active"] %>
   checked="1"
 <% endif %>
/> <%LOCALE id="50" string="No"%>
 <input type="radio" name="is_active" value="1"
 <% if data["user"]["is_active"] %>
   checked="1"
 <% endif %>
/> <%LOCALE id="49" string="Yes"%>
        <p/>
</td>
</tr>

<tr>
<td>
        <b><%LOCALE id="136" string="Is Admin?"%></b>
</td>
<td>
 <input type="radio" name="is_admin" value="0"
 <% if !data["user"]["is_admin"] %>
   checked="1"
 <% endif %>
/> <%LOCALE id="50" string="No"%>
 <input type="radio" name="is_admin" value="1"
 <% if data["user"]["is_admin"] %>
   checked="1"
 <% endif %>
/> <%LOCALE id="49" string="Yes"%>
        <p/>
</td>
</tr>

<tr>
<td colspan="2">
<button dojoType="button2" widgetId="chpass" onclick="enable_chpass();">
  <%LOCALE id="137" string="Change Password..."%>
</button>
<div dojoType="Container" id="passwordpane" style="display:none;">
<table>
<tr>
<td>
        <b><%LOCALE id="17" string="Password"%>:</b> 
</td>
<td>
<input type="password" size="32" name="password" value="" />
        <br />
</td>
</tr>
<tr>
<td>
        <b><%LOCALE id="67" string="Confirm Password"%>:</b>
</td>
<td>
 <input type="password" size="32" name="confirmpassword" value="" />
</td>
</tr>
</table>
</div>
</td>
</tr>

<tr>
<td colspan="2">
		<div dojoType="ComboPicker" loadAvailableFunction="getAvailable" loadMembersFunction="getMembers" addsId="added" removesID="removed"></div>
</td>
</tr>

<tr>
<td colspan="2">
        <p/>

        <input type="hidden" name="added" id="added"/>
        <input type="hidden" name="removed" id="removed"/>


        <button name="action" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
        <button name="action" value="Save"><%LOCALE id="127" string="Save"%></button>
</td>
</tr>
</table>

<%@include file="adminfooter.phtml"%>

<script type="text/javascript">
  dojo.require("dijit.form.Button");
  dojo.require("fins.widget.ComboPicker");
</script>

<script type="text/javascript">
function getMembers()
{
  var res = null;

<% if data["newgroup"] %>
    return [];
<% endif %>

  var bindArgs = {
    url:         "/admin/getgroups_json/" +  "<%$user.id%>" ,
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJson(data.toString());
        res = res.data;
    }
};

// dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
}

function getAvailable()
{
  var res = null;

  var bindArgs = {
    url:         "/admin/getgroups_json",
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJson(data.toString());
        res = res.data;
    }
};

    // dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
};
</script>

<script type="text/javascript">

   function enable_chpass()
   {
     var w = dijit.byId('chpass');

     if(w)
     {
       w.hide();
     }

     var p = dijit.byId('passwordpane');
     
     if(p)
       p.show();     
   }

   </script>
XXXX
<%@include file="adminfooter.phtml"%>
<%@include file="bottom.phtml"%>
