  <%@ include file="top.phtml" %>
  <%@ include file="adminheader.phtml" %>

   <title><%syspref var="site.name"%> :: admin :: edit group</title>

<script type="text/javascript">
dojo.require("dojo.json");
dojo.require("fins.widget.*");
dojo.require("fins.widget.ComboPicker");
</script>
<%@include file="pagebegin.phtml"%>
<div class="flash-message"><%flash %></div>

<% if data["newgroup"] %>
          <h3>New Group</h3>
<% else %>
          <h3>Edit Group</h3>
<% endif %>
	<form action="" method="post">
        <b>Group Name:</b> <input type="text" size="32" name="Name" value="<%$group.Name%>" />
        <p/>
        <input type="hidden" name="added" id="added"/>
        <input type="hidden" name="removed" id="removed"/>
<% if data["newgroup"] %>
        <input type="hidden" name="newgroup" value="1"/>
<% endif %>

<script type="text/javascript">
function getMembers()
{
  var res = null;

<% if data["newgroup"] %>
    return [];
<% endif %>

  var bindArgs = {
    url:         "/admin/getusers_json/" +  "<%$group.id%>" ,
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJson(data.toString());
        res = res.data;
    }
};

// dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
}

function getAvailable()
{
  var res = null;

  var bindArgs = {
    url:         "/admin/getusers_json",
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJson(data.toString());
        res = res.data;
    }
};

    // dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
};
</script>

		<div dojoType="ComboPicker" loadAvailableFunction="getAvailable" loadMembersFunction="getMembers" addsId="added" removesID="removed"></div>

<!--
        <p/>
        <b>Group Members</b><br/>

        <% foreach var="$group.groups" val="member" %>
        <%$member.Name%><br />
        <% end %>
-->
        <p/>
        <input type="submit" name="action" value="Cancel" />
        <input type="submit" name="action" value="Save" />
        </form>
        
<%@include file="footer.phtml"%>
<%@include file="bottom.phtml"%>

