<html>
<head>
  <%@include file="header.phtml"%>
   <title><%syspref var="site.name" %> :: admin :: acllist</title>
</head>
<body>
<%@include file="tagline.phtml"%>
   <div id="page-wrapper">
    <div id="page-content">
 
<div class="snip-buttons"> </div> 

<div class="flash-message"><%flash var="msg"%></div>
   <div class="snip-wrapper">
      <div class="snip-content">

          <h3>ACL List</h3>

<a href="newacl">New ACL...</a>
<p>
        
        <table>
            <tr><td>ACL 
Name</td><td>Description</td><td>e-mail</td><td></td></tr>  
          <% foreach var="acls" val="acl"%>
        <tr>
            <td><%$acl.Name%></td>
            <td><%$acl.Description%></td>
            <td>[ <a href="editacl?aclid=<%$acl.id%>">Edit</a> | 
                <a href="deleteacl?aclid=<%$acl.id%>">Delete</a> ]</td>
        </tr>
          <% end %>
        </table>
          
     </div>
      </div>
      </div>
      </div>
         
</div>

<div id="page-bottom"><a href="/space/contact+info">contact info</a> | Copyright 1995-2005 Bill 
Welliver</div>
</body>
</html>

