  <%@include file="top.phtml"%>
   <title><%syspref var="site.name" %> :: admin :: userlist</title>
  <%@include file="header.phtml" %>
  <%@include file="pagebegin.phtml" %>

<div class="flash-message"><%flash var="msg"%></div>
          <h3>User List</h3>

<a href="newuser">New User...</a>
<p>
        
        <table>
            <tr><td>User Name</td><td>Real Name</td><td>e-mail</td><td>Admin 
User?</td><td>Active?</td><td></td></tr>  
          <% foreach var="users" val="user"%>
        <tr>
            <td><%$user.UserName%></td>
            <td><%$user.Name%></td>
            <td><%$user.Email%></td>
            <td><a href="toggle_useradmin?userid=<%$user.id%>"><%boolean var="user.is_admin"%></a></td>
            <td><a href="toggle_useractive?userid=<%$user.id%>"><%boolean var="user.is_active"%></a></td>
            <td>[ <a href="edituser?userid=<%$user.id%>">Edit</a> | 
                <a href="deleteuser?userid=<%$user.id%>">Delete</a> ]</td>
        </tr>
          <% end %>
        </table>
          

  <%@include file="footer.phtml" %>
  <%@include file="bottom.phtml" %>


