  <%@include file="top.phtml" %>
   <title><%syspref var="site.name" %> :: admin :: grouplist</title>
  <%@include file="header.phtml" %>
  <%@include file="pagebegin.phtml" %>
<div class="flash-message"><%flash var="msg"%></div>

          <h3>Group List</h3>

<a href="editgroup?newgroup=1">New Group</a>
<p>
        
        <table>
            <tr><td>Group Name</td></tr>  
          <% foreach var="groups" val="group"%>
        <tr>
            <td><%$group.Name%></td>
            <td>[ <a href="editgroup?groupid=<%$group.id%>">Edit</a> | 
                <a href="deletegroup?groupid=<%$group.id%>">Delete</a> ]</td>
        </tr>
          <% end %>
        </table>
          
  <%@include file="footer.phtml" %>
  <%@include file="bottom.phtml" %>

