  <%@include file="top.phtml" %>
  <%@include file="adminheader.phtml" %>
   <title><%syspref var="site.name" %> :: admin :: <%LOCALE string="wip items"%></title>
  
  <%@include file="pagebegin.phtml" %>
<div class="flash-message"><%flash%></div>

          <h3><%LOCALE string="WIP Blog Entries"%></h3>
<p>
        <table>
            <tr><td><%LOCALE string="Path"%></td><td><%LOCALE string="Title"%></td><td><%LOCALE string="Author"%></td><td><%LOCALE string="Last Modified"%></td></tr>  
          <% foreach var="$wipblog" val="blog"%>
        <tr>
            <td><%$blog.path%></td>
            <td><%$blog.title%></td>
            <td><%$blog.author.Name%></td>
            <td><%$blog.current_version.nice_created%></td>
            <td>[ <a href="/exec/edit/<%$blog.path%>"><%LOCALE string="Edit"%></a> | 
                <a href="/exec/publish/<%$blog.path%>"><%LOCALE string="Publish"%></a> ]</td>
        </tr>
          <% end %>
   	<% if !sizeof(data->wipblog) %>
	  <tr><td colspan="5"> <%LOCALE string="No WIP Blog entries."%> </td></tr>
        <% endif %>
        </table>

          <h3><%LOCALE string="WIP Articles"%></h3>
<p>
        <table>
            <tr><td><%LOCALE string="Path"%></td><td><%LOCALE string="Title"%></td><td><%LOCALE string="Author"%></td><td><%LOCALE string="Last Modified"%></td></tr>  
          <% foreach var="$wipobj" val="obj"%>
        <tr>
            <td><%$obj.path%></td>
            <td><%$obj.title%></td>
            <td><%$obj.author.Name%></td>
            <td><%$obj.current_version.nice_created%></td>
            <td>[ <a href="/exec/edit/<%$obj.path%>"><%LOCALE string="Edit"%></a> | 
                <a href="/exec/publish/<%$obj.path%>"><%LOCALE string="Publish"%></a> ]</td>
        </tr>
          <% end %>
   	<% if !sizeof(data->wipobj) %>
	  <tr><td colspan="5"> <%LOCALE string="No WIP Documents."%> </td></tr>
        <% endif %>
        </table>
          
  <%@include file="footer.phtml" %>
  <%@include file="bottom.phtml" %>
