  <%@include file="top.phtml"%>
  <%@include file="adminheader.phtml" %>
   <title><%syspref var="site.name" %> :: admin :: <%LOCALE string="userlist"%></title>
  
  <%@include file="pagebegin.phtml" %>

<div class="flash-message"><%flash %></div>
          <h3><%LOCALE string="User List"%></h3>

<a href="newuser"><%LOCALE string="New User..."%></a>
<p>
        
        <table>
            <tr><td><%LOCALE string="User Name"%></td><td><%LOCALE string="Real Name"%></td><td><%LOCALE string="e-mail"%></td><td><%LOCALE string="Admin User?"%></td><td><%LOCALE string="Active?"%></td><td></td></tr>  
          <% foreach var="$users" val="user"%>
        <tr>
            <td><%$user.UserName%></td>
            <td><%$user.Name%></td>
            <td><%$user.Email%></td>
            <td><a href="toggle_useradmin?userid=<%$user.id%>"><%boolean var="$user.is_admin"%></a></td>
            <td><a href="toggle_useractive?userid=<%$user.id%>"><%boolean var="$user.is_active"%></a></td>
            <td>[ <a href="edituser?userid=<%$user.id%>"><%LOCALE string="Edit"%></a> | 
                <a href="deleteuser?userid=<%$user.id%>"><%LOCALE string="Delete"%></a> ]</td>
        </tr>
          <% end %>
        </table>          

  <%@include file="footer.phtml" %>
  <%@include file="bottom.phtml" %>

