 <%@include file="top.phtml" %>
  <%@include file="adminheader.phtml" %>
   <title><%syspref var="site.name" %> :: admin :: <%LOCALE string="list acls"%></title>
  
  <%@include file="pagebegin.phtml" %>

<div class="flash-message"><%flash %></div>
          <h3><%LOCALE string="ACL List"%></h3>

<a href="editacl?newacl=1"><%LOCALE string="New ACL..."%></a>
<p>
        
        <table>
            <tr><td><%LOCALE string="ACL Name"%></td><td><%LOCALE string="Description"%></td><td><%LOCALE string="e-mail"%></td><td></td></tr>  
          <% foreach var="$acls" val="acl"%>
        <tr>
            <td><%$acl.Name%></td>
            <td><%$acl.Description%></td>
            <td>[ <a href="editacl?aclid=<%$acl.id%>">Edit</a> | 
                <a href="deleteacl?aclid=<%$acl.id%>">Delete</a> ]</td>
        </tr>
          <% end %>
        </table>
          
  <%@include file="footer.phtml" %>
  <%@include file="bottom.phtml" %>
