<%@include file="top.phtml"%>
<title><%LOCALE id="162" string="Create Account"%></title>
<%@include file="adminheader.phtml"%>

<script type="text/javascript">
dojo.require("dojo.json");
dojo.require("fins.widget.ComboPicker");
</script>

<script type="text/javascript">
function getMembers()
{
  var res = null;

    return [];
}

function getAvailable()
{
  var res = null;

  var bindArgs = {
    url:         "/admin/getgroups_json",
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJson(data.toString());
        res = res.data;
    }
};

    // dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
};
</script>
<%@include file="pagebegin.phtml"%>
   <h3><%LOCALE id="163" string="New user"%></h3>

   <p>
<form action="" method="post">
<table>
<tr>
<td>
<b><%LOCALE id="134" string="Real Name"%>:</b>
</td>
<td>
 <input type="string" name="Name" value="<%$Name%>"/><br/>
</td>
</tr>
<tr>
<td>
<b><%LOCALE id="66" string="Username"%>:</b>
</td>
<td>
 <input type="string" name="UserName" value="<%$UserName%>"/><br/>
</td>
</tr>
<tr>
<td>
<b><%LOCALE id="68" string="Email"%>:</b>
</td>
<td>
 <input type="string" name="Email" value="<%$Email%>"><br/>
</td>
</tr>
<tr>
<td><b><%LOCALE id="17" string="Password"%>:</b>
</td>
<td>
 <input type="password" name="Password" value="<%$Password%>"/><br/>
</td>
</tr>
<tr>
<td>

<b><%LOCALE id="164" string="Re-type Password"%>:</b> </td><td> <input type="password" name="Password2"/>

<p/>
</td>
</tr>

<tr>
<td>
        <b><%LOCALE id="135" string="Is Active?"%></b>
</td>
<td>
 <input type="radio" name="is_active" value="0"/> <%LOCALE id="50" string="No"%>
 <input type="radio" name="is_active" value="1" checked="1"/> <%LOCALE id="49" string="Yes"%>
        <p/>
</td>
</tr>

<tr>
<td>
        <b><%LOCALE id="136" string="Is Admin?"%></b>
</td>
<td>
 <input type="radio" name="is_admin" value="0" checked="1"/> <%LOCALE id="50" string="No"%>
 <input type="radio" name="is_admin" value="1"/> <%LOCALE id="49" string="Yes"%>
        <p/>
</td>
</tr>

<tr>
<td colspan="2">
		<div dojoType="ComboPicker" loadAvailableFunction="getAvailable" loadMembersFunction="getMembers" addsId="added" removesID="removed"></div>
</td>
</tr>

<tr>
<td colspan="2">
        <input type="hidden" name="added" id="added"/>
        <input type="hidden" name="removed" id="removed"/>
<button type="submit" name="action" value="Create"><%LOCALE id="165" string="Create"%></button>
<button type="submit" name="action" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
</td>
</tr>
</table>

</form>
<p/>

<%@include file="footer.phtml"%>
<%@include file="bottom.phtml"%>
