<%@include file="top.phtml"%>
<title>Create Account</title>
<%@include file="adminheader.phtml"%>

<script type="text/javascript">
dojo.require("dojo.json");
dojo.require("fins.widget.ComboPicker");
</script>

<script type="text/javascript">
function getMembers()
{
  var res = null;

    return [];
}

function getAvailable()
{
  var res = null;

  var bindArgs = {
    url:         "/admin/getgroups_json",
    mimetype:   "text/plain",
    sync: true,
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here

        res = dojo.json.evalJson(data.toString());
        res = res.data;
    }
};

    // dispatch the request
    var requestObj = dojo.io.bind(bindArgs);

    return res;
};
</script>
<%@include file="pagebegin.phtml"%>
   <h3>New user</h3>

   <p>
<form action="" method="post">
<table>
<tr>
<td>
<b>Real Name:</b>
</td>
<td>
 <input type="string" name="Name" value="<%$Name%>"/><br/>
</td>
</tr>
<tr>
<td>
<b>Username:</b>
</td>
<td>
 <input type="string" name="UserName" value="<%$UserName%>"/><br/>
</td>
</tr>
<tr>
<td>
<b>Email:</b>
</td>
<td>
 <input type="string" name="Email" value="<%$Email%>"><br/>
</td>
</tr>
<tr>
<td><b>Password:</b>
</td>
<td>
 <input type="password" name="Password" value="<%$Password%>"/><br/>
</td>
</tr>
<tr>
<td>

<b>Re-type Password:</b> </td><td> <input type="password" name="Password2"/>

<p/>
</td>
</tr>

<tr>
<td>
        <b>Is Active?</b>
</td>
<td>
 <input type="radio" name="is_active" value="0"/> No
 <input type="radio" name="is_active" value="1" checked="1"/> Yes
        <p/>
</td>
</tr>

<tr>
<td>
        <b>Is Admin?</b>
</td>
<td>
 <input type="radio" name="is_admin" value="0" checked="1"/> No
 <input type="radio" name="is_admin" value="1"/> Yes
        <p/>
</td>
</tr>

<tr>
<td colspan="2">
		<div dojoType="ComboPicker" loadAvailableFunction="getAvailable" loadMembersFunction="getMembers" addsId="added" removesID="removed"></div>
</td>
</tr>



<tr>
<td colspan="2">
        <input type="hidden" name="added" id="added"/>
        <input type="hidden" name="removed" id="removed"/>
<input type="submit" name="action" value="Create"/>
<input type="submit" name="action" value="Cancel"/>
</td>
</tr>
</table>

</form>
<p/>

<%@include file="footer.phtml"%>
<%@include file="bottom.phtml"%>
