<html>
<head>
  <%@include file="header.phtml"%>
   <title><%$config.site.name%> :: admin :: userlist</title>
</head>
<body>
<%@include file="tagline.phtml"%>
   <div id="page-wrapper">
    <div id="page-content">
 
<div class="snip-buttons"> </div> 

<div class="flash-message"><%flash var="msg"%></div>
   <div class="snip-wrapper">
      <div class="snip-content">

          <h3>Application Settings</h3>


      </div>
      </div>
      </div>
      </div>
         
</div>

<div id="page-bottom"><a href="/space/contact+info">contact info</a> | Copyright 1995-2005 Bill 
Welliver</div>
</body>
</html>

