<html>
<head>
  <%@include file="header.phtml"%>
   <title><%syspref var="site.name" %> :: admin :: userlist</title>
</head>
<body>
<%@include file="tagline.phtml"%>
   <div id="page-wrapper">
    <div id="page-content">
 
<div class="snip-buttons"> </div> 

<div class="flash-message"><%flash %></div>
   <div class="snip-wrapper">
      <div class="snip-content">

          <h3>Application Settings</h3>


      </div>
      </div>
      </div>
      </div>
         
</div>

<div id="page-bottom"><a href="/space/contact+info">contact info</a> | Powered by <a
href="http://hww3.riverweb.com/space/pike/FinScribe">FinScribe</a></div>
</body>
</html>

