<html>
<head>
  <%@include file="header.phtml"%>
   <title><%syspref var="site.name" %> :: admin :: shutting down</title>
</head>
<body>
<%@include file="tagline.phtml"%>
   <div id="page-wrapper">
    <div id="page-content">
 
<div class="snip-buttons"> </div> 

<div class="flash-message"><%flash %></div>
   <div class="snip-wrapper">
      <div class="snip-content">

          <h3>Shutdown Begun</h3>
        
		This application will shut down in 5 seconds.
				
          
     </div>
      </div>
      </div>
      </div>
         
</div>

<div id="page-bottom"><a href="/space/contact+info">contact info</a> | Powered by <a 
href="http://hww3.riverweb.com/space/pike/FinScribe">FinScribe</a></div>
</body>
</html>

