  <%@include file="top.phtml"%>
  <%@include file="adminheader.phtml"%>
   <title><%syspref var="site.name" %> :: admin :: <%LOCALE id="176" string="shutting down"%></title>
  
<%@include file="pagebegin.phtml"%>

<div class="flash-message"><%flash %></div>

          <h3><%LOCALE id="177" string="Shutdown Begun"%></h3>
        
		<%LOCALE id="178" string="This application will shut down in 5 seconds."%>

<%@include file="footer.phtml"%>
<%@include file="bottom.phtml"%>
