  <%@include file="top.phtml"%>
  <%@include file="adminheader.phtml"%>
   <title><%syspref var="site.name" %> :: admin :: <%LOCALE string="shutting down"%></title>
  
<%@include file="pagebegin.phtml"%>

<div class="flash-message"><%flash %></div>

          <h3><%LOCALE string="Shutdown Begun"%></h3>
        
		<%LOCALE string="This application will shut down in 5 seconds."%>

<%@include file="footer.phtml"%>
<%@include file="bottom.phtml"%>
