 <%if data->user_object%>
<h2><%LOCALE string="Editing Categories"%></h2>
<p>
<%$flash%>
<p>
<form action="" method="post" id="editcategory-<%$obj%>">
<% foreach var="$object.categories" val="cat" %>
<a href="/exec/category/<%$cat.category %>"><%$cat.category %></a><br/>
<% end %>
<%LOCALE string="Existing Category"%>: <select name="existing-category">
<option value=""><%LOCALE string="Select a category"%>
<% foreach var="$existing-categories" val="ec" %><option><%$ec.category%>
<% end %>
</select> <%LOCALE string="or new category"%>: <input type="text" name="new-category" size="15" value=""/>
<p/>
<input type="hidden" id="action" name="action"/>
<input type="button" value="<%LOCALE string="Include"%>"
onclick="editCategory('<%$obj%>', 'editcategory-<%$obj%>', '<%LOCALE string="Include"%>')"/> 
&nbsp;
<input type="button" value="<%LOCALE string="Remove"%>"
onclick="editCategory('<%$obj%>', 'editcategory-<%$obj%>', '<%LOCALE string="Remove"%>')"/>
&nbsp;
<input type="button" value="<%LOCALE string="Close"%>"
onclick="closePopup(); return false"/>


</form>
<% endif %>

