 <%if data->user%>
<h2>Editing Categories</h2>
<p>
<%$flash%>
<p>
<form action="" method="post" id="editcategory-<%$obj%>">
<% foreach var="object.categories" val="cat" %>
<a href="/exec/category/<%$cat.category %>"><%$cat.category %></a><br/>
<% end %>
Existing Category: <select name="existing-category">
<option value="">Select a category
<% foreach var="existing-categories" val="ec" %><option><%$ec.category%>
<% end %>
</select> or new category: <input type="text" name="new-category"
size="15" value=""/>
<p/>
<input type="hidden" id="action" name="action"/>
<input type="button" value="Include"
onclick="editCategory('<%$obj%>', 'editcategory-<%$obj%>', 'Include')"/> 
&nbsp;
<input type="button" value="Remove"
onclick="editCategory('<%$obj%>', 'editcategory-<%$obj%>', 'Remove')"/>
&nbsp;
<input type="button" value="Close"
onclick="hideEditCategory(); return false"/>


</form>
<% endif %>
