  <%LOCALE string="This page"%> (<%$object.path%>) <%LOCALE string="contains"%> 
<% sizeof var="$object.attachments" %> <%LOCALE string="Attachments"%></a><br/>
  <table>
  <tr><td><strong><%LOCALE string="Name"%></strong></td>
      <td><strong><%LOCALE string="Type"%></strong></td>
      <td><strong><%LOCALE string="Size"%></strong></td>
      <td><strong><%LOCALE string="Updated"%></strong></td>
      <td><strong><%LOCALE string="Updated By"%></strong></td></tr>
  <% foreach var="$object.attachments" val="attachment" %>
  <tr><td><img src="/static/images/attachment/<%$attachment.icon%>"> <a href="/space/<%$attachment.path%>"><%$attachment.title%></a></td>
  <td><%$attachment.datatype.mimetype%></td>
  <td><%$attachment.current_version.nice_content_length%></td>
  <td><%$attachment.current_version.nice_created%></td>
  <td><%$attachment.current_version.author.Name%></td>
  </tr>
  <%end %>
  </table>
