  <%LOCALE id="79" string="This page"%> (<%$object.path%>) <%LOCALE id="80" string="contains"%> 
<% sizeof var="$object.attachments" %> <%LOCALE id="81" string="Attachments"%></a><br/>
  <table>
  <tr><td><strong><%LOCALE id="82" string="Name"%></strong></td>
      <td><strong><%LOCALE id="83" string="Type"%></strong></td>
      <td><strong><%LOCALE id="84" string="Size"%></strong></td>
      <td><strong><%LOCALE id="85" string="Updated"%></strong></td>
      <td><strong><%LOCALE id="86" string="Updated By"%></strong></td></tr>
  <% foreach var="$object.attachments" val="attachment" %>
  <tr><td><img src="/static/images/attachment/<%$attachment.icon%>"> <a href="/space/<%$attachment.path%>"><%$attachment.title%></a></td>
  <td><%$attachment.datatype.mimetype%></td>
  <td><%$attachment.current_version.nice_content_length%></td>
  <td><%$attachment.current_version.nice_created%></td>
  <td><%$attachment.current_version.author.Name%></td>
  </tr>
  <%end %>
  </table>
