  <table>
  <tr><td><strong>Name</strong></td>
      <td><strong>Size</strong></td>
      <td><strong>Created</strong></td>
      <td><strong>Created By</strong></td></tr>
  <% foreach var="objects" val="attachment" %>
  <tr><td><img src="/static/images/attachment/<%$attachment.icon%>"> <a href="/space/<%$attachment.path%>"><%$attachment.title%></a></td>
  <td><%$attachment.current_version.nice_content_length%></td>
  <td><%$attachment.current_version.nice_created%></td>
  <td><%$attachment.current_version.author.Name%></td>
  </tr>
  <%end %>
  </table>
