<% if data->object_is_weblog %>
<% else %>
  <% if data->user||data->numattachments!=0 %>
  <a id='link-attachments-<%$obj %>'
  onclick="toggleVisibility('attachments-<%$obj %>')"><img
  id="icon-attachments-<%$obj %>" src="/static/images/Icon-Unfold.png" border="0">
  <%$numattachments %> Attachments</a><br/>
  <div id="attachments-<%$obj %>" style="display:none;margin-left:20px">
  <table>
  <% foreach var="attachments" val="attachment" %>
  <tr><td><a href="/space/<%$attachment.path%>"><%$attachment.title%></a></td>
  <td><%$attachment.datatype.mimetype%></td>
  <td><%$attachment.current_version.content_length%></td></tr>
  <%end %>
  <%endif %>
 
  </table>

  <% if data->user %>

  <form action="/exec/upload" method="post" enctype="multipart/form-data">
  <input type="hidden" name="root" value="<%$obj %>"/>
  Attachment name: <input type="text" name="save-as-filename" size="35"/><br>
  File: <input name="upload-file" type="file"/>
  <br/>
  MimeType: <select name="mime-type">
  <% foreach var="datatypes" val="dt" %><option><%$dt.mimetype%>
  <% end %>
  </select>
  <br/>
  <input type="submit" name="action" value="Attach"/>
  </form>

  <% endif %>


</div>
<% endif %>
