<% if !data->object_is_weblog %>
<% if data->user %>

<a id='link-categories-<%$obj%>'
onclick="toggleVisibility('categories-<%$obj%>')"><img
id="icon-categories-<%$obj%>" src="/static/images/Icon-Unfold.png" 
border="0">
<%$numcategories%> Categories</a><br/>
<div id="categories-<%$obj%>" style="display:none;margin-left:20px">
<%$cfcontents%>
</div>
<% elseif data->numcategories %>
  Categories:
  <%foreach var="object.categories" val="cat" %>
    <a href="/exec/category/<%$cat.category%>"><%$cat.category%></a> &nbsp;
  <% end %>
<p/>

<% endif %>

<% endif %>
