
<%if data["object_is_weblog"] %>
<% elseif sizeof(data["object"]["attachments"])%>
<h3><%LOCALE id="81" string="Attachments"%></h3>
<%@ include file="space/_displayattachments.phtml"%>
<p/>
<%endif %>


<% if data["object_is_weblog"] %>
<% else %>
         <b><% if data["numcomments"] %>
                                         <a href="#" id="trigger_comments-<%$obj%>"><%$numcomments %> comments</a>
            <% else %>
                 <%LOCALE id="106" string="No comments"%> 
            <% endif %>
 |  <a id="PostComment" href="/exec/comments/<%$obj%>"><%LOCALE id="11" string="Post a Comment"%></a> | <a href="/rss/<%$obj%>?type=comments"><%LOCALE id="12" string="RSS Feed"%></a>
  <% if data["metadata"]["trackbacks"] %> | <a href="/exec/display_trackbacks/<%$obj%>" id="TrackBacks"><%sizeof var="$metadata.trackbacks"%> 
<%LOCALE id="100" string="TrackBacks"%></a> <% endif %>
  <% if data["metadata"]["pingbacks"] %> | <a href="/exec/display_pingbacks/<%$obj%>"><%sizeof var="$metadata.pingbacks"%> 
<%LOCALE id="101" string="PingBacks"%></a> <% endif %> | <a 
href="/exec/backlinks/<%$obj%>" id="BackLinks"><%LOCALE id="107" string="BackLinks"%></a>
         <p/>
                        <div dojoType="fins.widget.Comments" refreshUrl="/exec/getcomments/<%$obj%>" id="<%$obj%>_comments" connectorId="trigger_comments-<%$obj%>"></div>
<% endif %>
      </div>

</div>

