  <%@ include file="top.phtml" %>
  <%@ include file="header.phtml" %>
<title><%syspref var="site.name" %> :: <%$title%></title>
  <%@ include file="pagebegin.phtml" %>

  <%@include file="space/default_header.phtml"%>
<% if data["teaser"] %>
  <%$teaser%>
<% else %>
  <%render content="$content" object="$object"%>
<% endif %>
<p/>

  <%@include file="space/default_footer.phtml"%>
  <%@ include file="pageend.phtml" %>
  <%@ include file="footer.phtml" %>
  <%@ include file="bottom.phtml" %>

