<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:dc="http://purl.org/dc/elements/1.1/"
         xmlns:trackback="http://madskills.com/public/xml/rss/module/trackback/">
<rdf:Description
    rdf:about="<% syspref var="site.url"%>/space/<%$object.path%>"
    dc:identifier="<% syspref var="site.url"%>/space/<%$object.path%>"
    dc:title="<%$object.title%>"
    trackback:ping="<%syspref var="site.url"%>/exec/trackback/<%$object.path%>" />
</rdf:RDF>
