<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:dc="http://purl.org/dc/elements/1.1/"
         xmlns:trackback="http://madskills.com/public/xml/rss/module/trackback/">
<rdf:Description
    rdf:about="{config.site.url}/space/{obj}"
    dc:identifier="{config.site.url}/space/{obj}"
    dc:title="{object.title}"
    trackback:ping="{config.site.url}/exec/trackback/{obj}" />
</rdf:RDF>
