<html>
<head>
   <link rel="STYLESHEET" type="text/css" href="/space/themes/default/default.css" />
<title><%LOCALE id="90" string="Versions"%>: <%$object.title%></title>
</head>
<body>
<%@include file="tagline.phtml"%>

<%@include file="pagebegin.phtml"%>
   <h3><%LOCALE id="90" string="Versions"%>: <%$object.title%></h3>
<form action="/exec/diff/<%$object.path%>" method="post">
<table>
<tr>
<td><%LOCALE id="91" string="Version"%></td>
<td><%LOCALE id="92" string="Date Saved"%></td>
<td><%LOCALE id="93" string="Author"%></td>
<td><%LOCALE id="94" string="Diff from"%></td>
<td><%LOCALE id="95" string="Diff to"%></td>
</tr>
<% foreach var="$versions" val="version" %>
<tr>
<td>
  <%$version.version%> </td><td>
  <%$version.nice_created%> </td><td>
  <%$version.author.UserName%> </td><td>
  <input type="radio" name="from" value="<%$version.version%>"/></td><td>
  <input type="radio" name="to" value="<%$version.version%>"/></td>
  <td><a 
href="/space/<%$object.path%>?show_version=<%$version.version%>"><%LOCALE id="96" string="Show"%></a></td>
  </tr>
<% end %>
</table>
<br/>
<input type="submit" name="submit" value="<%LOCALE string="Show Differences"%>"/>
</form>

<%@include file="footer.phtml" %>
