<%$entry.nice_created%><br/>
<b><%$subject%> <a href="/space/<%$entry.path%>"><img src="/static/images/Icon-Permalink.png" width="8" 
height="9" alt="permalink" border="0"/></a></b>
<p/>
<%$contents%>
<p/><% if sizeof(data->entry["categories"]) %>
Posted in <% implode var="entry.category_links" final=" and " %> |
<% endif %><% sizeof var="entry.comments"%> Comments | <a href="/exec/comments/<%$entry.path%>">Post 
Comment</a> | <a href="/rss/<%$entry.path%>?type=comments">RSS Feed</a> | <a 
href="/exec/display_trackbacks/<%$entry.path%>"><% sizeof var="entry.md.trackbacks"%> TrackBacks</a> | <%$entry.md.views%> reads <a 
href="/space/<%$entry.path%>">&gt;&gt;</a><p/>
<p/>
