<%$entry.nice_created%><br/>
<b><%$subject%> <a href="/space/<%$entry.path%>"><img src="/static/images/Icon-Permalink.png" width="8" 
height="9" alt="permalink" border="0"/></a></b>
<p/>
  <%render content="$content" object="$entry"%>
<p/><% if sizeof(data->entry["categories"]) %> <%LOCALE string="Posted 
in"%> <% implode var="$entry.category_links" final=" and " %> |
<% endif %> <a onclick="displayComments('wiper<%$entry.id%>', '<%$entry.path%>'); return false;"><% sizeof 
var="$entry.comments"%> <%LOCALE string="comments"%></a></b> | <a 
href="/exec/comments/<%$entry.path%>"><%LOCALE string="Post Comment"%></a> 
| <a href="/rss/<%$entry.path%>?type=comments"><%LOCALE string="RSS Feed"%></a> | 
<a href="/exec/display_trackbacks/<%$entry.path%>"><% sizeof 
var="$entry.md.trackbacks"%> <%LOCALE string="TrackBacks"%></a> | <a 
href="/exec/display_pingbacks/<%$entry.path%>"><% sizeof var="$entry.md.pingbacks"%> <%LOCALE string="PingBacks"%></a> | <%$entry.md.views%> 
<%LOCALE string="reads"%> <a href="/space/<%$entry.path%>">&gt;&gt;</a><p/>
<div id="wiper<%$entry.id%>" style="display:none; padding-left:20px;"></div>
<p/>
