<html>
<head>
  <%@ include file="header.phtml" %>
   <title><%syspref var="site.name" %> :: <%$title %></title>
<script src="/static/javascripts/menulayer.js" type="text/javascript"></script>
<script src="/static/javascripts/rounded-corners.js" type="text/javascript"></script>

</head>
<body>
<%@ include file="tagline.phtml" %>
    <div id="page-wrapper">
    <div id="page-content">
      <% if data["object_is_weblog"] %>
      <% else %>
   <h3><%$title %></h3>
   Created by <%$author_username %>. Last updated by <%$editor_username %>, 
<%$when%>. Version #<%$version%>.
     <% endif %>


<% if data["user"]  %>
<div class="snip-buttons">
[ <a href="#" onclick="menuLayers.show('actions', '/exec/actions/<%$obj%>', event, this)" 
xonmouseout="menuLayers.hide()">actions</a> ]
</div>
<% endif %> 
<div id="actions" class="menu"><div id="closebutton" class="closebutton"><a onclick="menuLayers.hide()">Close</a></div>
<div id="actions_contents" class="action_contents"></div>
</div>

<div class="flash-message"><% flash var="msg" %></div>
   <div class="snip-wrapper">
      <div class="snip-content">
   <%@ include file="space/attachmentform.phtml" %>
<% if data["numcategories"] %>
 Posted in <% implode var="category_links" final=" and " %>.
<p/>
<% endif %>
         <%$content%>
<p/>
<% if data["object_is_weblog"] %>
<% else %>
<script type="text/javascript">
var comments_displayed = 0;

function displayComments(div, path, force)
{
  //if(comments_displayed != 0) return false;

  if(comments_displayed !=0)
    dojo.fx.html.wipeOut(document.getElementById(div), 100);

    var bindArgs = {
    url:         "/exec/getcomments/" + path,
    mimetype:   "text/plain",
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here
      document.getElementById(div).innerHTML = data.toString();
      dojo.fx.html.wipeIn(document.getElementById(div), 100);
    }
  };
    
    requestObj = dojo.io.bind(bindArgs);
    comments_displayed = 1;
  
  return false;
}
</script>
         <b><% if data["numcomments"] %>
                 <a href="#" onclick="displayComments('wiper', '<%$obj%>')"><%$numcomments %> comments</a></b>
            <% else %>
                 No comments 
            <% endif %>
 | <a href="#" onclick="openPopup('/exec/comments/<%$obj%>', '80%'); return false;">Post 
a Comment</a> | <a href="/rss/<%$obj%>?type=comments">RSS Feed</a>
  <% if data["metadata"]["trackbacks"] %> | <%$metadata.trackbacks%> TrackBacks <% endif %>
         <p/>
<div id="wiper" style="display:none;"></div>

<div id="commentsbox" style="background-color: #f5f5f5; opacity: .3;
filter: alpha(opacity=30); display: hidden; position: absolute; top: 100px; left: 50px; z-index: 10;"></div>

<% endif %>
         </div>
      </div>
      </div>
         <div id="page-portlet-1-wrapper">
          <div id="page-portlet-1">
         <% snip snip="themes/default/portlet-1" %>
         </div>
         </div>
         
</div>

<div id="page-bottom"><a href="/space/contact+info">contact info</a> | Copyright 1995-2005 Bill Welliver</div>
</body>
</html>
