<html>
<head>
  <%@ include file="header.phtml" %>
   <title><%syspref var="site.name" %> :: <%$title %></title>
<script src="/static/javascripts/menulayer.js" type="text/javascript"></script>

</head>
<body>
<%@ include file="tagline.phtml" %>
    <div id="page-wrapper">
    <div id="page-content">
      <% if data["object_is_weblog"] %>
      <% else %>
   <h3><%$title %></h3>
   Created by <%$author_username %>. Last updated by <%$editor_username %>, 
<%$when%>. Version #<%$version%>.
     <% endif %>


<% if data["user"]  %>
<div class="snip-buttons">
[ <a href="#" onclick="menuLayers.show('actions', '/exec/actions/<%$obj%>', event, this)" 
xonmouseout="menuLayers.hide()">actions</a> ]
</div>
<% endif %> 
<div id="actions" class="menu"><div id="closebutton" class="closebutton"><a onclick="menuLayers.hide()">Close</a></div>
<div id="actions_contents" class="action_contents"></div>
</div>

<div class="flash-message"><% flash var="msg" %></div>
   <div class="snip-wrapper">
      <div class="snip-content">
   <%@ include file="space/attachmentform.phtml" %>
   <%@ include file="space/categoryform.phtml" %>
<div id="postblog" style="display:none; width: 100%;">
</div>
         <%$content%>
<p/>
<% if data["object_is_weblog"] %>
<% else %>
<script type="text/javascript">
var comments_displayed = 0;

function showcomments(href, div, path)
{
  if(comments_displayed != 0) return false;

    var bindArgs = {
    url:         "/exec/getcomments/" + path,
    mimetype:   "text/plain",
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here
      document.getElementById(div).innerHTML = data.toString();
      dojo.fx.html.wipeIn(document.getElementById(div), 100);
    }
  };
    
    requestObj = dojo.io.bind(bindArgs);
    comments_displayed = 1;
  
  return false;
}
</script>
         <b><% if data["numcomments"] %>
                 <a href="#" onclick="javascript:showcomments(this, 
'wiper', '<%$obj%>')"><%$numcomments %> comments</a></b>
            <% else %>
                 No comments 
            <% endif %>
 | <a href="/exec/comments/<%$obj%>">Post a Comment</a> | <a href="/rss/<%$obj%>?type=comments">RSS Feed</a>
  <% if data["metadata"]["trackbacks"] %> | <%$metadata.trackbacks%> TrackBacks <% endif %>
         <p/>
<div id="wiper" style="display:none;"></div>
<% endif %>
         </div>
      </div>
      </div>
      </div>
         <div id="page-portlet-1-wrapper">
          <div id="page-portlet-1">
         <% snip snip="themes/default/portlet-1" %>
         </div>
         </div>
         
</div>

<div id="page-bottom"><a href="/space/contact+info">contact info</a> | Copyright 1995-2005 Bill Welliver</div>
</body>
</html>
