<h3><%LOCALE id="189" string="Commenting"%>: <%$obj%></h3>

   <p>

<div id="articlecontents" style="overflow: auto">
   <%$object%>
</div>
<p/>

<form action="" id="postcomments" method="post">
<table>
<% if data["anonymous"] %>


<tr>
<td>
<b><%LOCALE id="82" string="Name"%>:</b>
</td>
<td>
 <input type="text" size="35" name="name" value="<%$name%>"><br/>
</td>
</tr>
<tr>
<td>
<b><%LOCALE id="68" string="Email"%>:</b> 
</td>
<td>
<input type="text" size="35" name="email" value="<%$email%>"><br/>
</td>
</tr>
<tr>
<td>
<b><%LOCALE id="190" string="Website"%>:</b> 
</td>
<td>
<input type="text" size="35" name="website" value="<%$website%>">
</td>
</tr>
<tr>
<td>
<b><%LOCALE id="423" string="Authenticate"%>:</b> 
</td>
<td>
  <div dojoType="fins.widget.Recaptcha" public_key="<%syspref var="plugin.reCAPTCHA support.public-key" %>" id="comment_recaptcha"></div>
</td>
</tr>
<% endif %>
<tr>
<td>
</td>
<td>
<textarea rows="10" cols="80" name="contents"><%$contents%></textarea>
<br>
</td>
</tr>
<tr>
<td colspan="2">
<% if data["ajax"] %>
<input type="hidden" id="postaction" name="action">
<button type="button" onclick="document.getElementById('postaction').value='Preview'; saveComment('<%$obj%>', 'postcomments', 1); return 
false;" value="Preview"><%LOCALE id="191" string="Preview"%></button>
<button type="button" onclick="closePopup(); return false;" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
<button type="button" onclick="document.getElementById('postaction').value='Save'; saveComment('<%$obj%>', 'postcomments', 1);" 
value="Save"><%LOCALE id="127" string="Save"%></button>
<% else %>
<button type="submit" name="action" value="Preview"><%LOCALE id="191" string="Preview"%></button>
<button type="submit" name="action" value="Save"><%LOCALE id="127" string="Save"%></button>
<% endif %>
</td>
</tr>
</table>
</form>

<% if data->preview %>
<%LOCALE id="191" string="Preview"%>:<p>
<%$preview%>
<% endif %>
