   <h3>Commenting: <%$obj%></h3>

   <p>

<div id="articlecontents" style="height: 200px; overflow: auto">
   <%$object%>
</div>
<p/>

<form action="" id="postcomments" method="post">
<table>
<% if data["anonymous"] %>
<tr>
<td>
<b>Name:</b>
</td>
<td>
 <input type="text" size="35" name="name" value="<%$name%>"><br/>
</td>
</tr>
<tr>
<td>
<b>Email:</b> 
</td>
<td>
<input type="text" size="35" name="email" value="<%$email%>"><br/>
</td>
</tr>
<tr>
<td>
<b>Website:</b> 
</td>
<td>
<input type="text" size="35" name="website" value="<%$website%>">
</td>
</tr>
<tr>
<td colspan="2">
<p>
<script type="text/javascript"
   src="http://api.recaptcha.net/challenge?k=<%syspref var="recaptcha.public_key" %>">
</script>

<noscript>
   <iframe src="http://api.recaptcha.net/noscript?k=<%syspref var="recaptcha.public_key" %>"
       height="300" width="500" frameborder="0"></iframe><br>
   <textarea name="recaptcha_challenge_field" rows="3" cols="40">
   </textarea>
   <input type="hidden" name="recaptcha_response_field" 
       value="manual_challenge">
</noscript>
<p>
</td>
</tr>
<% endif %>
<tr>
<td>
</td>
<td>
<textarea dojoType="resizabletextarea" rows="20" cols="80" name="contents"><%$contents%></textarea>
<br>
</td>
</tr>
<tr>
<td colspan="2">
<% if data["ajax"] %>
<input type="hidden" id="postaction" name="action">
<input type="button" onclick="document.getElementById('postaction').value='Preview'; postComment('<%$obj%>', 'postcomments', 1); return false;" value="Preview">
<input type="button" onclick="closePopup(); return false;" value="Cancel">
<input type="button" onclick="document.getElementById('postaction').value='Save'; saveComment('<%$obj%>', 'postcomments', 1);" value="Save">
<% else %>
<input type="submit" name="action" value="Preview">
<input type="submit" name="action" value="Save">
<% endif %>
</td>
</tr>
</table>
</form>

<% if data->preview %>
Preview:<p>
<%$preview%>
<% endif %>
