<h2>Editing Attachments</h2>
<p>
<%$flash%>
<p>

<% if data->object_is_weblog %>
  You can't directly add attachments to a weblog page.
<% else %>
  This page (<%$object.path%>) contains <%$numattachments %> Attachments</a><br/>
  <table>
  <tr><th>Name</th><th>Type</th><th>Size</th><th></th></tr>
  <% foreach var="attachments" val="attachment" %>
  <tr><td><img src="/static/images/attachment/<%$attachment.icon%>"> <a href="/space/<%$attachment.path%>"><%$attachment.title%></a></td>
  <td><%$attachment.datatype.mimetype%></td>
  <td><%$attachment.current_version.content_length%></td>
  <td><a onclick="document.getElementById('action').value='Delete'; 
document.getElementById('filename').value='<%$attachment.path%>'; saveAttachment('<%$object.path%>', 
'attachmentform'); return false;">Delete</a></td>
  </tr>
  <%end %>
  </table>
  <form action="" method="post" enctype="multipart/form-data" id="attachmentform"> 
<table>
<tr>
<td>
<b> Attachment name: </b>
</td>
<td id="filename-div">
</td>
</tr>
<tr>
<td>
<b>  File: </b>
</td>
<td>
<input name="upload-file" type="file" onchange="updateFilename(this)"/>
</td>
</tr>
<tr>
<td colspan="2">
  <input type="hidden" name="action" id="action"/>
  <input type="button" onclick="document.getElementById('action').value='Add'; saveAttachment('<%$object.path%>', 
'attachmentform'); return false;" value="Add"/>

<input type="hidden" id="filename" name="save-as-filename" size="35"/>

</td>
</tr>
</table>
  </form>
<% endif %>

