<form action="/exec/login" id="loginform" method="post">
<table>
<tr>
<td>
<input type="hidden" name="return_to" value="<%$return_to%>"/>
<%LOCALE id="203" string="Login"%>: 
</td><td>
<input type="string" id="username" name="username" value="<%$username%>"/><br/>
</td>
</tr>
<tr>
<td>
<%LOCALE id="17" string="Password"%>:</td><td>
 <input type="password" name="password"/></td></tr>
<tr><td colspan="2">
<%if !data->ajax %>
<script type="text/javascript">
var f = document.getElementById("username");
f.focus();
</script>
<% endif %>
<p/>
<button type="submit" name="action" value="Login"><%LOCALE id="203" string="Login"%></button>
<% if !data->ajax %>
<button type="submit" name="action" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
<% else %>
<button type="submit" name="action" onclick="return closePopup()" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
<% endif %>
</td>
</tr>
</table>
</form>
<p/>
<a href="/exec/forgotpassword"><%LOCALE id="204" string="Forgot password?"%></a>
<% if data->autocreate %>
|
<a href="/exec/createaccount"><%LOCALE id="205" string="Create an account"%></a>
<%endif%>

