<form action="" method="post" id="postblogform">
Subject: <input type="text" name="subject" size="40" value="<%$subject%>"/>
<br/>
<textarea rows="20" cols="80" name="contents"><%$contents%></textarea>
<br/>
TrackBack URLs (click preview to detect <a href="http://en.wikipedia.org/wiki/Trackback">TrackBack</a> URLs):<br/>
<textarea rows="5" cols="80" name="trackbacks"><%$trackbacks%></textarea> 
<br/>
Publish Date: <input type="text" size="15" <%$showcreated%> id="createdDate" name="createddate" value="<%$createddate%>"/ >
<input type="checkbox" name="created_toggle" <%$createchecked%> onclick="toggleCreated()"/>
<br/>
<% if data->ajax %>
<input type="hidden" name="ajax" value="1"/>
<input type="hidden" id="postformajaxaction" name="action" value="" />
<input type="submit" onclick="document.getElementById('postformajaxaction').value='Preview'; postBlog('postblog', 
'<%$object.path%>', 'postblogform'); return false;" name="action" value="Preview"/>
<input type="submit" 
onclick="document.getElementById('postformajaxaction').value='Cancel'; postBlog('postblog', 
'<%$object.path%>', 'postblogform'); return false;" name="action" value="Cancel"/>
<input type="submit" 
onclick="document.getElementById('postformajaxaction').value='Save'; postBlog('postblog', 
'<%$object.path%>', 'postblogform'); return false;" name="action" value="Save"/>
<% else %>
<input type="hidden" name="ajax" value="1"/>
<input type="submit" name="action" value="Preview"/>
<input type="submit" name="action" value="Cancel"/>
<input type="submit" name="action" value="Save"/>
<% endif %>

</form>

<%if data->preview %>
<b>Preview:</b><p/>
<%$preview%>
<% endif %>
