<script type="text/javascript">
 dojo.require("dojo.widget.*");
 dojo.require("dojo.widget.DropdownDatePicker");
</script>
<div style="text-align:left">
<h3><%LOCALE id="206" string="Posting"%>: <%$obj%></h3>
<form action="" method="post" id="postblogform">
<table>
<tr>
<td>
<b><%LOCALE id="194" string="Subject"%>:</b> 
</td>
<td>
<input type="text" name="subject" size="40" value="<%$subject%>"/>
<br/>
</td>
</tr>
<tr>
<td></td>
<td>
<textarea xdojoType="resizabletextarea" rows="20" cols="80" name="contents"><%$contents%></textarea>
<br/>
</td>
</tr>
<tr>
<td>
<b><%LOCALE id="207" string="TrackBack URLs"%>: </b>
<br>(<%LOCALE id="208" string="click preview to detect"%> <a 
href="http://en.wikipedia.org/wiki/Trackback"><%LOCALE id="209" string="TrackBack"%></a> <%LOCALE id="210" string="URLs"%>)
<br/>
</td>
<td>
<textarea xdojoType="resizabletextarea" rows="5" cols="80" name="trackbacks"><%$trackbacks%></textarea> 
<br/>
</td>
</tr>
<tr>
<td>
<b><%LOCALE id="211" string="Publish Date"%>: </b>
</td>
<td>
<input type="text" size="15" 
 id="createdDate" name="createddate"
<%$showcreated%>
value="<%$createddate%>" dojoType="DropDownDatePicker" />
<input type="checkbox" name="created_toggle" 
<%$createchecked%> 
onclick="toggleCreated()"/>
</td>
</tr>
<tr>
<td colspan="2">
<% if data->ajax %>
<input type="hidden" name="ajax" value="1"/>
<input type="hidden" id="postformajaxaction" name="action" value="" />

<button type="button" onclick="document.getElementById('postformajaxaction').value='Preview'; postBlog('popup_contents', '<%$object.path%>', 'postblogform'); return false;" name="action" value="Preview"><%LOCALE id="191" string="Preview"%></button>
<button type="button" onclick="closePopup(); return false;" name="action" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
<button type="button" onclick="document.getElementById('postformajaxaction').value='Save'; postBlog('popup_contents', '<%$object.path%>', 'postblogform'); return false;" name="action" value="Save"><%LOCALE id="127" string="Save"%></button>
<button type="button" onclick="document.getElementById('postformajaxaction').value='Post'; postBlog('popup_contents', '<%$object.path%>', 'postblogform'); return false;" name="action" value="Post"><%LOCALE id="212" string="Post"%></button> 
<% else %>
<button type="submit" name="action" value="Preview"><%LOCALE id="191" string="Preview"%></button>
<button type="submit" name="action" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
<button type="submit" name="action" value="Save"><%LOCALE id="127" string="Save"%></button>
<button type="submit" name="action" value="Post"><%LOCALE id="212" string="Post"%></button>
<% endif %>
</td>
</tr>
</table>
</form>

<%if data->preview %>
<b><%LOCALE id="191" string="Preview"%>:</b><p/>
<%$preview%>
<% endif %>

</div>


<script type="text/javascript">
function postOnLoad()
{
alert("foo");
dojo.debug("loading dojo widgets...");
     var parser = new dojo.xml.Parse();
     var frag = parser.parseElement(dojo.byId("postblogform"), null, true);
     dojo.widget.getParser().createComponents(frag);
}
</script>

