  <script type="text/javascript">
	var reporter = function(reporter) {
		this.name = "titleClick";
		this.go = function(message) {
			dojo.debug("message: " + message.node.data);
			if(message &&  message.node && message.node.data != undefined)
			{
			  var m = message.node.data;
			  window.location = (m);
			}
		    return false;
		}
	}

    function init() {
		var pageTree = dojo.widget.manager.getWidgetById('treeSelector');

			dojo.event.topic.subscribe(
				pageTree.eventNames.select,
				new reporter('pageTree'),
				'go'
			);

		var rootNode = dojo.widget.manager.getWidgetById('pageroot');
		var controller = dojo.widget.manager.getWidgetById('treeController');
                controller.expand(rootNode);
    };

//    dojo.addOnLoad(init);

  </script>



<dl dojoType="fins:ObjectTreeContextMenu"  id="treeContextMenu">
<dt class="dojo-TreeMenuItemV3" id="ctxMenuAdd" caption="Add Child">
<dt class="dojo-TreeMenuItemV3" id="ctxMenuDel" caption="Remove Item">
</dl>

<div dojoType="TreeRpcControllerV3" RpcUrl="/exec/tree" widgetId="treeController"></div>
<div dojoType="TreeSelectorV3" widgetId="treeSelector"></div>
<div dojoType="TreeV3" listeners="treeSelector;treeController;treeContextMenu" actionsDisabled="addChild" widgetId="pageTree" isFolder="true">
    <div dojoType="TreeNodeV3" widgetId="pageroot" title="Contents" isFolder="true" actionsDisabled="remove">
	</div>
</div>

