<% if data["user_object"]  %>
<b>Page Actions</b>
<ul>
  <% if data["iseditable"] %> <li> <a href="/exec/edit/<%$object.path%>">edit</a><% else %> edit <% 
endif %> page content

<p>
 <% if data["iseditable"] %> 
<li> <a href="#" onclick="openPopup('/exec/editattachments/<%$object.path%>', '60%');return false;">edit</a> attachments
<li> <a href="#" onclick="openPopup('/exec/editcategory/<%$object.path%>', '60%');return false;">edit</a> categories
 <% endif %>
<p>
  <% if data["iseditable"] %> <li> <a href="/exec/move/<%$object.path%>">move</a><% else %> move 
<% 
endif %> page

  <% if data["isdeleteable"] %> <li> <a 
href="/exec/delete/<%$object.path%>">delete</a><% else %> delete 
<% 
endif %> page

  <% if data["islockable"] %>
	<% if data["islocked"] %> <li> <a href="/exec/toggle_lock/<%$object.path%>">unlock</a> this page
        <% else %> 
             <li> <a href="/exec/toggle_lock/<%$object.path%>">lock</a> this page
        <% endif %> 
      <% if data["comments_closed"] %>
       <li> <a href="/exec/toggle_comments/<%$object.path%>">enable</a> comments
     <% else %>
       <li> <a href="/exec/toggle_comments/<%$object.path%>">disable</a> comments
     <% endif %>
  <% endif %>

<li> <a href="/exec/versions/<%$object.path %>">versions</a> of this page

<p>
<li> <a href="/exec/new?currentpage=<%$object.path%>">new</a> page

</ul>
<% else %>
You are not logged in. 
<% endif %>

