<% if data["user_object"]  %>
<b><%LOCALE id="213" string="Page Actions"%></b>
<ul>
  <% if data["iseditable"] %> <li> <a href="/exec/edit/<%$object.path%>"><%LOCALE id="214" string="edit page content"%></a><% else %> <%LOCALE id="214" string="edit page content"%> 
<% endif %> 

<p>
 <% if data["iseditable"] %> 
<li> <a href="#" 
onclick="openAttachments('<%$object.path%>', '<%sessionid%>');return false;"><%LOCALE id="215" string="edit attachments"%></a>
<li> <a href="#" onclick="openPopup('/exec/editcategory/<%$object.path%>', '60%');return false;"><%LOCALE id="216" string="edit categories"%></a>
 <% endif %>
<p>
  <% if data["iseditable"] %> <li> <a href="/exec/move/<%$object.path%>"><%LOCALE id="217" string="move page"%></a><% else %> <%LOCALE id="217" string="move page"%> 
<% endif %>

  <% if data["isdeleteable"] %> <li> <a 
href="/exec/delete/<%$object.path%>"><%LOCALE id="218" string="delete"%></a><% else %> <%LOCALE id="219" string="delete page"%> 
<% endif %>

  <% if data["islockable"] %>
	<% if data["islocked"] %> <li> <a href="/exec/toggle_lock/<%$object.path%>"><%LOCALE id="220" string="unlock this page"%></a>
        <% else %> 
             <li> <a href="/exec/toggle_lock/<%$object.path%>"><%LOCALE id="221" string="lock this page"%></a>
        <% endif %> 
      <% if data["comments_closed"] %>
       <li> <a href="/exec/toggle_comments/<%$object.path%>"><%LOCALE id="222" string="enable comments"%></a>
     <% else %>
       <li> <a href="/exec/toggle_comments/<%$object.path%>"><%LOCALE id="223" string="disable comments"%></a>
     <% endif %>
  <% endif %>

<li> <a href="/exec/versions/<%$object.path %>"><%LOCALE id="224" string="versions of this page"%></a>

<li> <a href="/exec/info/<%$object.path %>"><%LOCALE id="225" string="get info"%></a>

<p>
<li> <a href="/exec/new?currentpage=<%$object.path%>"><%LOCALE id="226" string="new page"%>
</ul>
<p>
<%LOCALE id="227" string="Current ACL"%>: 
<%if data["isdeleteable"] %>
<a href="/exec/changeacl/<%$object.path%>"><%$object.acl.name%></a>
<% else %>
<%$object.acl.name%>
<% endif %>
<br>
<%LOCALE id="228" string="Object Type"%>: 
<% if data["object"]["is_attachment"] == 3 %>
  <%LOCALE id="229" string="WIP Blog Entry"%> <% if data["object"]->is_postable(data["user_object"]) %> <a 
href="/exec/publish/<%$object.path%>"><%LOCALE id="158" string="Publish"%></a> <% endif %>
<% elseif data["object"]["is_attachment"] == 2 %>
  <%LOCALE id="230" string="Published Blog Entry"%>
<% elseif data["object"]["is_attachment"] == 1 %>
  <%LOCALE id="231" string="Attachment"%>
<% else %>
  <%LOCALE id="232" string="Published Object"%>
<% endif %>
<% else %>
<%LOCALE id="233" string="You are not logged in."%>
<% endif %>

