<html>
<head>
  <%@include file="header.phtml" %>
   <title><%$config.site.name%> :: Category <%$category.category%></title>
</head>
<body>
<%@ include file="tagline.phtml" %>
   <div id="page-wrapper">
    <div id="page-content">
   <h3><%$category.category%></h3>
<% if data->user %><div class="snip-buttons"> [ <a href="/exec/edit/<%obj%>">edit</a> ] </div> 
<% endif %>
<div class="flash-message"><%flash var="msg" %></div>
   <div class="snip-wrapper">
      <div class="snip-content">
Items in this category:
<ul>
<% foreach var="objects" val="o" %>
  <li> <a href="/space/<%$o.path%>"><%$o.title%></a>
<% end %>
</ul>
<p/>
         </div>
      </div>
      </div>
      </div>
         <div id="page-portlet-1-wrapper">
          <div id="page-portlet-1">
         <% snip snip="themes/default/portlet-1" %>
         </div>
         </div>
         
</div>

<div id="page-bottom"><a href="/space/contact+info">contact info</a> | Copyright 1995-2005 Bill Welliver</div>
</body>
</html>
