  <%@include file="top.phtml" %>
  <%@include file="header.phtml" %>
   <title><%syspref var="site.name" %> :: <%LOCALE id="235" string="Category"%> <%$category.category%></title>
  <%@include file="pagebegin.phtml" %>

   <h3><%$category.category%></h3>
<div class="flash-message"><%flash %></div>

<%LOCALE id="236" string="Items in this category"%>:
<p>
<%@include file="space/_objectlist.phtml"%>
<p/>

<%action_link controller="/rss" args="$category.category" type="category"%><img src="/static/images/feed-icon-12x12.png" width="12" height="12" alt="[RSS]" border="0"></a>
<%action_link controller="/rss" args="$category.category" type="category"%><%LOCALE id="12" string="RSS Feed"%></a>

  <%@include file="pageend.phtml" %>
  <%@include file="footer.phtml" %>
  <%@include file="bottom.phtml" %>

