<%@include file="top.phtml"%>
<title><%syspref var="site.name" %> :: select acl</title>
<%@include file="header.phtml"%>
<%@include file="pagebegin.phtml" %>
   <h3>Choose a new ACL</h3>
Document: <b><%$obj%></b>
<br/>
Current ACL: <b><%$currentacl.Name%></b>
<p>
<form>
<input type="hidden" name="return_to" value="<%$return_to%>"/>
New ACL: <select name="newacl">
<% foreach var="$acls" val="acl" %>
<option value="<%$acl.id %>"><%$acl.Name%>
<% end %>
</select>
<input type="submit" value="Change">
</form>
<%@include file="footer.phtml" %>
<%@include file="bottom.phtml" %>
