<html>
<head>
   <link rel="STYLESHEET" type="text/css" href="/space/themes/default/default.css" />
   <title>Commenting: <%$config.site.name%></title>
</head>
<body>
<%@include file="tagline.psp"%>
<%@include file="pagebegin.psp"%>
   <h3>Commenting: <%$obj%></h3>

   <p>


   <%$object%>

<p/>

<form action="" method="post">
<textarea rows="20" cols="80" name="contents"><%$contents%></textarea>
<br>
<input type="submit" name="action" value="Preview">
<input type="submit" name="action" value="Save">
</form>

<% if data->preview %>
Preview:<p>
<%$preview%>
<% endif %>

<%@include file="footer.psp"%>

