<html>
<head>
    <link rel="STYLESHEET" type="text/css" href="/space/themes/default/default.css" />
<title>Create Account</title>
</head>
<body>
<%@include file="tagline.phtml"%>
<%@include file="pagebegin.phtml"%>
   <h3>Create account</h3>

   <p>
<form action="" method="post">
<table>
<tr>
<td>
<b>Your name:</b>
</td>
<td>
 <input type="string" name="Name" value="<%$Name%>"/><br/>
</td>
</tr>
<tr>
<td>
<b>Username:</b>
</td>
<td>
 <input type="string" name="UserName" value="<%$UserName%>"/><br/>
</td>
</tr>
<tr>
<td>
<b>Email:</b>
</td>
<td>
 <input type="string" name="Email" value="<%$Email%>"><br/>
</td>
</tr>
<tr>
<td><b>Password:</b>
</td>
<td>
 <input type="password" name="Password" value="<%$Password%>"/><br/>
</td>
</tr>
<tr>
<td>

<b>Re-type Password:</b> </td><td> <input type="password" name="Password2"/>

<p/>
</td>
</tr>
<tr>
<td colspan="2">
<input type="submit" name="action" value="Create"/>
<input type="submit" name="action" value="Cancel"/>
<input type="hidden" name="return_to" value="<%$return_to%>"/>
</td>
</tr>
</table>

</form>
<p/>
<%@include file="footer.phtml"%>
