<%@include file="top.phtml"%>
<title><%LOCALE id="162" string="Create Account"%></title>
<%@include file="header.phtml"%>
<%@include file="pagebegin.phtml"%>
   <h3><%LOCALE id="241" string="Create account"%></h3>
   <p>
<form action="" method="post">
<table>
<tr>
<td>
<b><%LOCALE id="242" string="Your name"%>:</b>
</td>
<td>
 <input type="string" name="Name" value="<%$Name%>"/><br/>
</td>
</tr>
<tr>
<td>
<b><%LOCALE id="66" string="Username"%>:</b>
</td>
<td>
 <input type="string" name="UserName" value="<%$UserName%>"/><br/>
</td>
</tr>
<tr>
<td>
<b><%LOCALE id="68" string="Email"%>:</b>
</td>
<td>
 <input type="string" name="Email" value="<%$Email%>"><br/>
</td>
</tr>
<tr>
<td><b><%LOCALE id="17" string="Password"%>:</b>
</td>
<td>
 <input type="password" name="Password" value="<%$Password%>"/><br/>
</td>
</tr>
<tr>
<td>

<b><%LOCALE id="164" string="Re-type Password"%>:</b> </td><td> <input type="password" name="Password2"/>

<p/>
</td>
</tr>
<tr>
<td colspan="2">
<button type="submit" name="action" value="Create"><%LOCALE id="165" string="Create"%></button>
<button type="submit" name="action" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
<input type="hidden" name="return_to" value="<%$return_to%>"/>
</td>
</tr>
</table>

</form>
<p/>
<%@include file="footer.phtml"%>
<%@include file="bottom.phtml"%>

