
<%@include file="top.phtml" %>
<title><%syspref var="site.name" %> :: <%LOCALE id="243" string="deleting object"%></title>
<%@include file="header.phtml" %>
<%@include file="pagebegin.phtml" %>
   <h3><%LOCALE id="244" string="Delete an existing object"%></h3>

<form action="" method="post">
<%LOCALE id="245" string="Current location"%>: <%$object.path%><br/>

<% if data["getconfirm"] %>

  <% if data["movesub"] %>
  <%LOCALE id="246" string="Deleting all subcontent as well."%>
  <% endif %>
<input type="hidden" size="40" name="movesub" value="<%$movesub%>"/><p>

<% if data["affected"] %>
  <%LOCALE id="247" string="The following objects will be deleted"%>:

  <% foreach var="$affected" val="afo" %>
    <li><%$afo.path%>
  <% end %>
<p>
<% endif %>

<button type="submit" name="action" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
<button type="submit" name="action" value="Really Delete"><%LOCALE id="123" string="Really Delete"%></button>

<% else %>
<%LOCALE id="248" string="Delete all documents under  this location as well?"%> 
<input type="checkbox" name="movesub" value="1" <%if data["movesub"] %>checked="1" <% endif %>/>
<p/>
<button type="submit" name="action" value="Cancel"><%LOCALE id="122" string="Cancel"%></button>
<button type="submit" name="action" value="Delete"><%LOCALE id="146" string="Delete"%></button>
<p>
<i><%LOCALE id="249" string="Note"%>:</i> <%LOCALE id="250" string="deleting established document locations is not recommended, as existing links may be broken. Be sure to update any existing documents that link to the objects being deleted."%>

<% endif %>

</form>

<%@include file="footer.phtml" %>
<%@include file="bottom.phtml" %>

