  <%@include file="top.phtml" %>
   <title><%syspref var="site.name" %> :: <%LOCALE string="Trackbacks for"%> <%$object.title%></title>
  <%@include file="header.phtml" %>
  <%@include file="pagebegin.phtml" %>
<h3><%LOCALE string="Trackbacks for"%> <%$object.title%></h3>

<%LOCALE string="The trackback URL for this article is"%>: 
<a 
href="<%syspref var="site.url"%>/exec/trackback/<%$object.path%>"><%syspref var="site.url"%>/exec/trackback/<%$object.path%></a>.
<%foreach var="$trackbacks" val="trackback" %>
<a href="<%$trackback.url%>"><%$trackback.url%></a><br/>
<%$trackback.excerpt%>
<hr/>
<% end %>
  <%@include file="footer.phtml" %>
  <%@include file="bottom.phtml" %>

