  <%@include file="top.phtml" %>
  <%@include file="header.phtml" %>
   <title><%syspref var="site.name" %> :: <%LOCALE id="252" string="Pingbacks for"%> <%$object.title%></title>
  <%@include file="pagebegin.phtml" %>

<h3><%LOCALE id="252" string="Pingbacks for"%> <%$object.title%></h3>
<ol>
<%foreach var="$pingbacks" val="pingback" %>
<li><a href="<%$pingback%>"><%$pingback%></a>
<% end %>
</ol>
<hr/>
  <%@include file="pageend.phtml" %>
  <%@include file="footer.phtml" %>
  <%@include file="bottom.phtml" %>

