<html>
<head>
  <%@include file="header.phtml" %>
   <title><%$config.site.name%> :: Trackbacks for <%$object.title%></title>
</head>
<body>

   <div class="snip-wrapper">
      <div class="snip-content">

The trackback URL for this article is: <%$config.site.url%>/exec/trackback/<%$object.path%>.

<%foreach var="trackbacks" val="trackback" %>
<%$trackback.url%><br/>
<%$trackback.excerpt%>
<hr/>
<% end %>

      </div>
         
</div>
</body>
</html>

