  <%@include file="top.phtml" %>
   <title><%syspref var="site.name" %> :: <LOCALE string="Pingbacks for"%> <%$object.title%></title>
  <%@include file="header.phtml" %>
  <%@include file="pagebegin.phtml" %>
<h3><LOCALE string="Pingbacks for"%> <%$object.title%></h3>
<ol>
<%foreach var="$pingbacks" val="pingback" %>
<li><a href="<%$pingback%>"><%$pingback%></a>
<% end %>
</ol>
<hr/>
  <%@include file="footer.phtml" %>
  <%@include file="bottom.phtml" %>

