<%@ include file="top.phtml" %>
<%@ include file="header.phtml" %>
<title><%syspref var="site.name" %> :: editing <%$obj%></title>
<%@ include file="pagebegin.phtml" %>

   <h3>Editing: <%$obj%></h3>


<form action="" method="post" id="editform">
Subject: <input type="text" size="40" name="subject" value="<%$subject%>"/><br>
<%$contentswidget %>
<br>
<input type="hidden" name="datatype" value="<%$datatype %>">
<input type="submit" name="action" value="Preview">
<input type="submit" name="action" value="Cancel">
<input type="submit" name="action" value="Save">
</form>

<%if data->preview%>
Preview:<p>
<%$preview%>
<%endif %>

<%@include file="footer.phtml"%>
<%@include file="bottom.phtml"%>

