<html>
<head>
   <link rel="STYLESHEET" type="text/css" href="/space/themes/default/default.css" />
<title><%$config.site.name%> :: editing <%$obj%></title>
</head>
<body>
<%@ include file="tagline.phtml" %>

{include:pagebegin.phtml}
   <h3>Editing: <%$obj%></h3>


<form action="" method="post">
Subject: <input type="text" size="40" name="subject" value="<%$subject%>"/><br>
<textarea rows="20" cols="80" name="contents"><%$contents%></textarea>
<br>
<input type="submit" name="action" value="Preview">
<input type="submit" name="action" value="Save">
</form>

<%if data->preview%>
Preview:<p>
<%$preview%>
<%endif %>

<%@include file="footer.phtml"%>
