<%@include file="top.phtml"%>
<title><%LOCALE id="257" string="Password Retrieval"%></title>
<%@include file="header.phtml"%>
<%@include file="pagebegin.phtml"%>
   <h3><%LOCALE id="257" string="Password Retrieval"%></h3>
<p/>
<div class="flash-message"><font color="red"><%flash %></font></div>
<p/>

<%LOCALE id="258" string="Enter your username in the form below and click on 'Locate.' Your account password will be emailed to the address on record for that account."%>
   <p/>
<%action_form controller="/exec" action="forgotpassword" method="post"%>
<input type="hidden" name="return_to" value="<%$return_to%>"/>
<%LOCALE id="66" string="Username"%>: <input type="string" name="username" value="<%$username%>"/><br/>
<p/>
<button type="submit" name="action" value="Locate"><%LOCALE id="259" string="Locate"%></button>
</form>
<%@include file="footer.phtml"%>
<%@include file="bottom.phtml"%>

