<%@include file="top.phtml"%>
<title><%LOCALE string="Password Retrieval"%></title>
<%@include file="header.phtml"%>
<%@include file="pagebegin.phtml"%>
   <h3><%LOCALE string="Password Retrieval"%></h3>
<p/>
<%LOCALE string="Enter your username in the form below and click on 'Locate.' Your account password will be emailed to the address on record for that account."%>
   <p/>
<form action="" method="post">
<%LOCALE string="Username"%>: <input type="string" name="UserName" value="<%$UserName%>"/><br/>
<p/>
<button type="submit" name="action" value="Locate"><%LOCALE string="Locate"%></button>
</form>
<%@include file="footer.phtml"%>
<%@include file="bottom.phtml"%>

