<%@include file="top.phtml" %>
<title><%syspref var="site.name" %> :: <%LOCALE string="moving object"%></title>
<%@include file="header.phtml" %>
<%@include file="pagebegin.phtml" %>
   <h3><%LOCALE string="Move an existing object"%></h3>

<form action="" method="post">
<%LOCALE string="Current location"%>: <%$object.path%><br/>

<% if data["getconfirm"] %>

<%LOCALE string="New Object path"%>: <%$newpath%> 
  <% if data["movesub"] %>
  <br/>
  <%LOCALE string="Moving all subcontent as well."%>
  <% endif %>
<input type="hidden" size="40" name="newpath" value="<%$newpath%>"/><br>
<input type="hidden" size="40" name="movesub" value="<%$movesub%>"/><p>

<% if data["affected"] %>
  <%LOCALE string="The following objects will be moved"%>:

  <% foreach var="$affected" val="afo" %>
    <li><%$afo.path%>
  <% end %>
<p>
<% endif %>

<button type="submit" name="action" value="Cancel"><%LOCALE string="Cancel"%></button>
<button type="submit" name="action" value="Really Move"><%LOCALE string="Really Move"%></button>

<% else %>
<input type="text" size="40" name="newpath" value="<%$newpath%>"/><br>
<br>
<%LOCALE string="Move all documents under  this location as well?"%>
<input type="checkbox" name="movesub" value="1" <%if data["movesub"] %>checked="1" <% endif %>/>
<p/>
<button type="submit" name="action" value="Cancel"><%LOCALE string="Cancel"%></button>
<button type="submit" name="action" value="Move"><%LOCALE string="Move"%></button>
<p>
<i><%LOCALE string="Note"%>:</i> <%LOCALE string="moving established document locations is not recommended, as existing links may be broken. Be sure to update any existing documents that link to the objects being moved."%>

<% endif %>

</form>

<%@include file="footer.phtml" %>
<%@include file="bottom.phtml" %>
