<html>
<head>
   <link rel="STYLESHEET" type="text/css" href="/space/themes/default/default.css" />
<title><%syspref var="site.name" %> :: creating object</title>
</head>
<body>
<%@include file="tagline.phtml" %>

<%@include file="pagebegin.phtml" %>
   <h3>Create new object</h3>

<form action="" method="post">
<table>
<tr>
<td>
<b>Object path:</b>
</td>
<td>
<input type="text" size="40" name="title" value=""/><br>
</td>
</tr>
<tr>
<td>
<b>Object type:</b>
</td>
<td>
<select  id="datatype" name="datatype">
<% foreach var="datatypes" val="dt" %>
<option value="<%$dt.mimetype %>"><%$dt.name %>
<% end %>
</select>

<script type="text/javascript">
  var d = document.getElementById('datatype');
  if(d) d.value = '<%$datatype%>';
</script>

<br>
</td>
</tr>
<tr>
<td colspan="2">
<input type="submit" name="action" value="Create">
</td>
</tr>
</table>
</form>

<%@include file="footer.phtml" %>
