<%@include file="top.phtml"%>
<title><%syspref var="site.name" %> :: creating object</title>
<%@include file="header.phtml"%>
<%@include file="pagebegin.phtml" %>
   <h3>Create new object</h3>

<form action="/exec/new/<%$currentpage%>" method="post">
<table>
<%if data["currentpage"] %>
<tr>
<td colspan="2">
<input type="hidden" name="currentpage" value="<%$currentpage%>"/>
Create a new page:
<p/>
<input type="radio" name="pageloc" value="subpage" checked="1"/> as a subpage of <b><%$object.path %></b>. <br/>
  <%if data["parentobject"] %>
<input type="radio" name="pageloc" value="parentpage" /> as a subpage of <b><%$parentobject.path %></b>. <br/>
  <% endif %>
<input type="radio" name="pageloc" value="manual" /> by specifying the path manually. <br/>
</td>
</tr>
<tr>
<td>
<b>Object name or path</b>:
</td>
<td>
<input type="text" size="40" name="title" value=""/><br>
(no leading or trailing slashes, please)
</td>
</tr>
<% else %>
<tr>
<td>
<b>Full Object path</b>:
</td>
<td>
<input type="text" size="40" name="title" value=""/><br>
(no leading or trailing slashes, please)
</td>
</tr>
<% endif %>
<tr>
<td>
<b>Object type:</b>
</td>
<td>
<select  id="datatype" name="datatype">
<% foreach var="datatypes" val="dt" %>
<option value="<%$dt.mimetype %>"><%$dt.name %>
<% end %>
</select>

<script type="text/javascript">
  var d = document.getElementById('datatype');
  if(d) d.value = '<%$datatype%>';
</script>

<br>
</td>
</tr>
<tr>
<td colspan="2">
<input type="submit" name="action" value="Create">
</td>
</tr>
</table>
</form>

<%@include file="footer.phtml" %>
<%@include file="bottom.phtml" %>

