<html>
<head>
   <link rel="STYLESHEET" type="text/css" href="/space/themes/default/default.css" />
<title><%syspref var="site.name" %> :: creating object</title>
</head>
<body>
<%@include file="tagline.phtml" %>

<%@include file="pagebegin.phtml" %>
   <h3>Create new object</h3>

<form action="" method="post">
Object path: <input type="text" size="40" name="title" value=""/><br>
<select name="datatype">
<option value="text/wiki">Wiki
<option value="text/html">HTML
</select>
<br>
<input type="submit" name="action" value="Create">
</form>

<%@include file="footer.phtml" %>
