<html>
<head>
   <link rel="STYLESHEET" type="text/css" href="/space/themes/default/default.css" />
<title>Posting: <%$obj%></title>
<script type="text/javascript" src="/static/javascripts/dojo.js"></script>
<script type="text/javascript">
                dojo.require("dojo.fx.*");
                dojo.require("dojo.widget.DatePicker");
</script>
</head>
<body>
<%@include file="tagline.phtml" %>

<%@include file="pagebegin.phtml" %>
   <h3>Posting: <%$obj%></h3>


<form action="" method="post">
Subject: <input type="text" name="subject" size="40" value="<%$subject%>"/>
<br/>
<textarea rows="20" cols="80" name="contents"><%$contents%></textarea>
<br/>
TrackBack URLs (click preview to detect <a href="http://en.wikipedia.org/wiki/Trackback">TrackBack</a> URLs):<br/>
<textarea rows="5" cols="80" name="trackbacks"><%$trackbacks%></textarea> 
<br/>
<script type="text/javascript">
function showDatePicker() {
var block = document.getElementById("datePicker");
var picker;
if (!block) {
var body = dojo.html.body();
block = document.createElement("div");
block.setAttribute("id", "datePicker");
block.style.display = "none";
block.style.position = "absolute";
block.style.zIndex = "400";
block.style.background = "Window";
block.style.backgroundColor = "white";
block.style.border = "1px solid #efefef";
var inputField = document.getElementById("createdDate");
var offsets = cumulativeOffset(inputField);
block.style.top = offsets[1] + 15 + 'px';
block.style.left = offsets[0] + 'px';
body.appendChild(block);

picker = dojo.widget.fromScript("DatePicker",
{widgetId: "datePickerPicker"}, block, "last");
dojo.event.kwConnect({srcObj: picker,srcFunc:"onSetDate",targetObj: this, targetFunc:"setDateField", 
once:true});
}
dojo.fx.html.fadeShow(block, 200);
}

function cumulativeOffset(element) {
var valueT = 0, valueL = 0;
do {
valueT += element.offsetTop || 0;
valueL += element.offsetLeft || 0;
element = element.offsetParent;
} while (element);
return [valueL, valueT];
} 
  function setDateField(evt) {

        document.getElementById("datePicker").style.display="none";

        var field = document.getElementById("createdDate");

        var date = dojo.widget.manager.getWidgetById("datePickerPicker").date;

        field.value = dojo.date.toString(date, "#yyyy-#MM-#dd");

    }

	function toggleCreated()
	{

		var field = document.getElementById("createdDate");
		field.disabled = !field.disabled;
                if(!field.disabled)
                  showDatePicker();
	}
</script>
Publish Date: <input type="text" size="15" <%$showcreated%> id="createdDate" name="createddate" value="<%$createddate%>"/ >
<input type="checkbox" name="created_toggle" <%$createchecked%> onclick="toggleCreated()"/>
<br/>
<input type="submit" name="action" value="Preview"/>
<input type="submit" name="action" value="Cancel"/>
<input type="submit" name="action" value="Save"/>
</form>

<%if data->preview %>
<b>Preview:</b><p/>
<%$preview%>
<% endif %>
<%@include file="footer.phtml" %>
