<html>
<head>
   <link rel="STYLESHEET" type="text/css" href="/space/themes/default/default.css" />
<title>Posting: <%$obj%></title>
</head>
<body>
<%@include file="tagline.phtml" %>

<%@include file="pagebegin.phtml" %>
   <h3>Posting: <%$obj%></h3>


<form action="" method="post">
Subject: <input type="text" name="subject" size="40" value="<%$subject%>"/>
<br/>
<textarea rows="20" cols="80" name="contents"><%$contents%></textarea>
<br/>
TrackBack URLs (click preview to detect <a href="http://en.wikipedia.org/wiki/Trackback">TrackBack</a> URLs):<br/>
<textarea rows="5" cols="80" name="trackbacks"><%$trackbacks%></textarea> 
<br/>
<script type="text/javascript">
	function toggleCreated()
	{
		document.forms[0].address.disabled = !document.forms[0].address.disabled;
	}
</script>
Publish Date: <input type="text" size="15" name="created"/ > <input type="checkbox" name="created_toggle" onclick="toggleCreated()"/>
<br/>
<input type="submit" name="action" value="Preview"/>
<input type="submit" name="action" value="Cancel"/>
<input type="submit" name="action" value="Save"/>
</form>

<%if data->preview %>
<b>Preview:</b><p/>
<%$preview%>
<% endif %>
<%@include file="footer.phtml" %>
