<%@ include file="top.phtml"%>
<%@include file="header.phtml"%>
<title><%LOCALE id="0" string="Search Results for"%> '<%$q%>'</title>
<%@include file="pagebegin.phtml"%>

<h3><%LOCALE id="0" string="Search Results for"%> '<%$q%>'</h3>

<p>
<div class="flash-message"><font color="red"><%flash %></font></div>
<p>
<%searchresults%>
<%@ include file="pageend.phtml"%>
<%@ include file="footer.phtml"%>
<%@ include file="bottom.phtml"%>



