<%LOCALE id="287" string="Dear"%> <%syspref var="site.name" %> <%LOCALE id="288" string="user"%>,

<%LOCALE id="289" string="You recently requested that your password for your account be mailed to you."%>

<%LOCALE id="290" string="Your password is:"%> <%$password%>

<%LOCALE id="291" string="If you did not request this, someone else may be attempting to break into"%>
<%LOCALE id="292" string="your account. If this is the case, please report this by contacting your"%>
<%syspref var="site.name" %> <%LOCALE id="293" string="system administrator."%>

<%LOCALE id="294" string="Sincerely,"%>

<%LOCALE id="295" string="The"%> <%syspref var="site.name" %> <%LOCALE id="296" string="Gnomes"%>
