<%LOCALE id="287" string="Dear"%> <%$name%>,

<%LOCALE id="" string="A new account has been created for you."%>

<%LOCALE id="" string="Website:"%> <%syspref var="site.name"%>
<%LOCALE id="" string="Your username is:"%> <%$username%>

<%LOCALE id="291" string="If you did not request this, someone else may be attempting to break into"%>
<%LOCALE id="292" string="your account. If this is the case, please report this by contacting your"%>
<%syspref var="site.name" %> <%LOCALE id="" string="system administrator by replying to this email."%>

<%LOCALE id="294" string="Sincerely,"%>

<%LOCALE id="295" string="The"%> <%syspref var="site.name" %> <%LOCALE id="296" string="Gnomes"%>
