<%LOCALE string="Dear"%> <%syspref var="site.name" %> <%LOCALE string="user"%>,

<%LOCALE string="You recently requested that your password for your account be mailed to you."%>

<%LOCALE string="Your password is:"%> <%$password%>

<%LOCALE string="If you did not request this, someone else may be attempting to break into"%>
<%LOCALE string="your account. If this is the case, please report this by contacting your"%>
<%syspref var="site.name" %> <%LOCALE string="system administrator."%>

<%LOCALE string="Sincerely,"%>

<%LOCALE string="The"%> <%syspref var="site.name" %> <%LOCALE string="Gnomes"%>
