Dear <%syspref var="site.name" %> user,

You recently requested that your password for your account be mailed to you.

Your password is: <%$password%>

If you did not request this, someone else may be attempting to break into
your account. If this is the case, please report this by contacting  your 
<%syspref var="site.name" %> system administrator.

Sincerely,

The <%syspref var="site.name" %> Gnomes
