<html>
<head>
   <link rel="STYLESHEET" type="text/css" href="/space/themes/default/default.css" />
<title>Versions: {object.title}</title>
</head>
<body>
<%@include file="tagline.phtml"%>

<%@include file="pagebegin.phtml"%>
   <h3>Versions: <%$object.title%></h3>
<form action="/exec/diff/<%$object.path%>" method="post">
<table>
<tr>
<td>Version</td>
<td>Date Saved</td>
<td>Author</td>
<td>Diff from</td>
<td>Diff to</td>
</tr>
<%foreach var="versions" val="version"%>
<tr>
<td>
  <%$version.version%> </td><td>
  <%$version.nice_created%> </td><td>
  <%$version.author.UserName%> </td><td>
  <input type="radio" name="from" value="<%$version.version%>"/></td><td>
  <input type="radio" name="to" value="<%$version.version%>"/></td>
  <td><a href="/space/<%$object.path%>?show_version=<%$version.version%>">Show</a></td>
  </tr>
<%end %>
</table>
<br/>
<input type="submit" name="submit" value="Show Differences"/>
</form>

<%@include file="footer.phtml"%>

