Host: <input type="text" value="localhost" id="mysqlhost" 
name="mysqlhost"/><br/>
User: <input type="text" value="finscribe" id="mysqluser"  
name="mysqluser"/><br/>
Password: <input type="password" value="finscribe" 
id="mysqlpassword" name="mysqlpassword"/><br/>
Database: <input type="text" value="finscribe" id="mysqldatabase" 
name="mysqldatabase"/><br/>

<script type="text/javascript">
function makedburl()
{
  var url = "mysql://" + document.getElementById("mysqluser");
  url += ":";
  url += document.getElementById("mysqlpassword");
  url += "@";
  url +=  document.getElementById("mysqlhost");
  url += "/";
  url +=  document.getElementById("mysqldatabase");
  updatedburl(url);
}
</script>
