<html>
<head>
<title>FinScribe Installer</title>
<script type="text/javascript" src="/static/javascripts/dojo.js"></script>
<script type="text/javascript">
	dojo.require("dojo.widget.Wizard");
	dojo.hostenv.writeIncludes();

    function cancel() {
        alert("Wizard Cancelled!");
    }

    function done() {
	window.location="/";
    }

function updatedburl(url)
{
  var requestObj;
  var v = document.getElementById("db");
  var url = "/install/makedburl/";

    var bindArgs = {
    url:         null,
    sync: true,
    formNode: document.getElementById("dbconfiguratorform"),      
    mimetype:   "text/plain",
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here
        var e = document.getElementById("dburl");
        if(!(e))
          return;
        else  
        {
          e.value = data.toString();
        }
    }
  };

    bindArgs.url = url + v.value;
    requestObj = dojo.io.bind(bindArgs);
}

function selectdb()
{
  var requestObj;
  var v = document.getElementById("db");
  var url = "/install/getdburlconfigurator/";

    var bindArgs = {
    url:         null,
    mimetype:   "text/plain",
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here
        var d = document.getElementById("dburlconfigurator");
        if(!d)
          return;
        d.innerHTML = data.toString();
    }
  };

    bindArgs.url = url + v.value;
    requestObj = dojo.io.bind(bindArgs);
}

function verifyandcreate()
{
  updatedburl();

  var requestObj;
  var v = document.getElementById("db");
  var url = "/install/verifyandcreate/";
  var result = false;

    var bindArgs = {
    url:         url,
    sync: true,
    formNode: document.getElementById("dbconfiguratorform"),
    mimetype:   "text/plain",
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here
        if(data.toString() != "true")
           result = data.toString();
    }
  };

    bindArgs.url = url + v.value;
    requestObj = dojo.io.bind(bindArgs);

    if(result) return "We failed to connect to the database.\n"
                     + result;
}


function populateprefs()
{
  updatedburl();

  var requestObj;
  var url = "/install/populateprefs/";
  var result = false;

    var bindArgs = {
    url:         url,
    sync: true,
    formNode: null,
    mimetype:   "text/plain",
    error:      function(type, errObj){
    },
    load:      function(type, data, evt){
        // handle successful response here
        if(data.toString() != "true")
           result = data.toString();
    }
  };

    bindArgs.url = url;
    bindArgs.formNode = document.getElementById("preferenceform1"),
    requestObj = dojo.io.bind(bindArgs);
    if(result) return "We failed to set the application preferences.\n"
                     + result;

    bindArgs.formNode = document.getElementById("preferenceform2"),
    requestObj = dojo.io.bind(bindArgs);
    if(result) return "We failed to set the application preferences.\n"
                     + result;

    bindArgs.formNode = document.getElementById("adminuserform1"),
    bindArgs.url = "/install/createadminuser/";
    requestObj = dojo.io.bind(bindArgs);

    if(result) return "We failed to create the administrative account.\n"
                     + result;

}

function checkadmin()
{
  var v = document.getElementById("adminuser");
  if(v.value == null || v.value == "")
    alert("You must provide an administrative username.");
  v = document.getElementById("confirmadminpassword");
  var v1 = document.getElementById("adminpassword");
  if(v.value.length < 4)
  {
    alert("You must provide an administrative password that is at least 4 characters long.");
  }
  else if(v.value != v1.value)
  {
    alert("Your administrative password and its confirmation do not match.");
  }
}
</script>

<style type="text/css">
body {
	font-family : sans-serif;
}

</style>
</head>

<body>

<div id="wizard" dojoType="wizard" style="width:100%; height:350px;">
<div dojoType="WizardPane" label="Welcome!">
<h1>Welcome to FinScribe</h1>

We're glad you've chosen to install FinScribe. 
<p>
The first step in getting 
FinScribe up and running is to configure the database and install the 
FinScribe objects. You'll also answer a few question about how you'd like 
the application to work. 
<p>
When you're finished with this wizard, your FinScribe install will be 
complete!

</div>

<div dojoType="WizardPane" label="Database Configuration (1)" 
passFunction="verifyandcreate">
<h1>Select a database</h1>
FinScribe supports several database types for the storage of data. Please 
choose a database storage type from the list of available drivers below.
<p>

<form action="#" id="dbconfiguratorform">
<b>Database type:</b> <select name="db" id="db" onChange="selectdb()">
<option>Select a DB
<% foreach var="dbs" val="db" %>
<option><%$db%>
<% end %>
</select>

<input type="hidden" name="dburl" id="dburl" value=""/>

<div id="dburlconfigurator">
</div>
</form>

Please verify this information before continuing. The database you've 
specified 
must already exist (in the case of SQLite, that means that the path must 
be writable). 
<p>
When you click "next", we will attempt to connect to the database you've 
specified and create the FinScribe objects. If the attempt fails, you can 
return to the previous page to correct your information. 
</div>

<div dojoType="WizardPane" label="Database Configuration (3)" 
canGoBack="false">
<h1>Database Objects Created</h1>
We will now proceed to configure your copy of FinScribe.
<p>
On the next few pages are a few questions that we will use to personalize your application.
</div>
<div dojoType="WizardPane" label="Application Configuration" 
canGoBack="false">
<form action="#" id="preferenceform1">
<h1>Site Basics</h1>
<table>
<tr><td>
<b>Site URL:</b>
</td>
<td>
<input type="text" name="pref.site.url" value=""><br/>
<input type="hidden" name="type.site.url" value="string">
</td></tr>
<tr>
<td colspan="2">
This is the URL that users will enter to access your site (it should be the root, such as http://www.mysite.com/).
</td>
</tr>

<tr>
</td></tr>
<tr>
<td>
<b>Site Name:</b>
</td>
<td>
<input type="text" name="pref.site.name" value=""><br/>
<input type="hidden" name="type.site.name" value="string">
</td></tr>
<tr>
<td colspan="2">
This is the name for your website. It is used in the default templates. An example might be: "Joe's Weblog".
</td>
</tr>
<tr>
<td>
<b>Site Logo File:</b>
</td><td>
 <input type="text" name="pref.site.logo" value=""><br/>
<input type="hidden" name="type.site.logo" value="string">
</td></tr>
<tr>
<td colspan="2">
You may specify the URL of an image that will be displayed in the default page layout template.
</td>
</tr>
<tr>
<td>
<b>Site Tagline:</b>
</td><td>
<input type="text" name="pref.site.tagline" value=""><br/>
<input type="hidden" name="type.site.tagline" value="string">
</td></tr>
<tr><td colspan="2">
A short phrase describing your website. Displayed in the default page layout template. Example: "all the news that interests me".
</td></tr>
<tr>
<td>
<b>Track Views:</b>
</td><td> 
<input type="radio" name="pref.site.track_views" value="1" checked="1" /> Yes
<input type="radio" name="pref.site.track_views" value="0" /> No<br/>
<input type="hidden" name="type.site.track_views" value="boolean">
</td>
</tr>
<tr><td colspan="2">
Should FinScribe track page view counts (aggregated)? You may turn this feature off for a (possibly negligible) speed increase.
</td></tr>
</table>
</form>
</div>
<div dojoType="WizardPane" label="Application Configuration">
<form action="#" id="preferenceform2">
<h1>Administration</h1>
<table>
<tr>
<td><b>
Mail Host:
</b></tr><td> 
<input type="text" name="pref.mail.host" value="" /><br/>
<input type="hidden" name="type.mail.host" value="string">
</td></tr>
<tr><td colspan="2">
FinScribe uses an SMTP mail host to send emails. Please specify the preferred host here.
</td></tr>
<tr>
<td><b>
Mail Return Address:
</b></tr><td> 
<input type="text" name="pref.mail.return_address" value="" /><br/>
<input type="hidden" name="type.mail.return_address" value="string">
</td></tr>
<tr><td colspan="2">
Use this preference to specify the return address for any email sent by the FinScribe engine (such as for lost password retrieval, 
etc).
</td></tr>
<tr>
<td><b>
Account Autocreate:
</b></tr><td> 
<input type="radio" name="pref.administration.autocreate" value="1" checked="1" /> Yes 
<input type="radio" name="pref.administration.autocreate" value="0" /> No
<input type="hidden" name="type.administration.autocreate" value="boolean">
<br/>
</td></tr>
<tr><td colspan="2">
Enabling Autocreate will allow users to self register.
</td></tr>
<tr>
<td><b>
Weblog.com PING:
</b></tr><td> 
<input type="radio" name="pref.blog.weblog_ping" value="1" checked="1" /> Yes
<input type="radio" name="pref.blog.weblog_ping" value="0" /> No<br/>
<input type="hidden" name="type.blog.weblog_ping" value="boolean">
</td></tr>
<tr>
<td colspan="2">
Should FinScribe "ping" Weblogs.com when you post a new entry to a weblog?
</td></tr>
</table>
</form>
</div>
<div dojoType="WizardPane" label="Administrative User" passFunction="checkadmin">
<h1>Administrative User Setup</h1>
<form action="#" id="adminuserform1">
Please specify the username, password and email address for this FinScribe's administrative user. An 
administrative user has full permission to change settings and content in on your FinScribe site. You can 
set up additional users (regular and administrative) once you complete this wizard. 
<p>
In the mean time, you'll use this account to log in and configure your site further.
<p>
<table>
<tr>
<td><b>
Username:
</b></tr><td> 
<input type="text" size="16" id="adminuser" name="adminuser" value="admin"/> <br/>
</td></tr>
<tr><td colspan="2">
</td></tr>
<tr>
<td><b>
Password:
</b></tr><td> 
<input type="password" size="16" id="adminpassword"  name="adminpassword"/> <br/>
</td></tr>
<tr><td colspan="2">
</td></tr>
<tr>
<td><b>
Confirm Password:
</b></tr><td> 
<input type="password" size="16" id="confirmadminpassword" name="confirmadminpassword"/> <br/>
</td></tr>
<tr><td colspan="2">
</td></tr>
<tr>
<td><b>
Email:
</b></tr><td> 
<input type="text" size="64" name="adminemail"/> 
</td></tr>
<tr><td colspan="2">
</td></tr>
</table>
</form>
</div>
<div dojoType="WizardPane" label="Application Configuration" passFunction="populateprefs">
<h1>Preparing to configure</h1>
We're now ready to configure your FinScribe installation. At this time, you may wish to go back and 
confirm the information you've provided on the previous pages. 
<p>
When you click "next", we will configure FinScribe using the information you've provided. We will also 
set up a few starter objects so that you'll be able to get started adding content right away.
</div>
<div dojoType="WizardPane" label="Application Configuration" doneFunction="done">
<h1>Setup Complete!</h1>
Congratulations! Your FinScribe installation is complete and ready to use.
<p>
Click "done" below to visit your FinScribe site.
</div>
</div>


</html>
