<!-- this is 2header.phtml -->
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>general.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>wiki.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>snip.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>page.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>style.css"/>
   <link rel="STYLESHEET" type="text/css" href="/static/lightbox.css"/>
   <script src="<% theme show="path"%>functions.js"></script>

<script src="/static/javascripts/SWFUpload.js"></script>

<xscript type='text/javascript'>
  djConfig = {
    isDebug : true,
    disableFlashStorage : true
  };

</xscript>
  <xscript src="/static/javascripts/dojo.js"></script>
<xscript type='text/javascript'>
dojo.hostenv.setModulePrefix("fins", "fins/");
</xscript>

<div style="display:none" id="object"><%$obj%></div>
