<!-- this is adminfooter.phtml -->
         </div>
      </div>
      </div>
      </div>

</div>

<div id="page-bottom"><a href="/space/contact info"><%LOCALE id="1" string="contact info"%></a> | <%LOCALE id="2" string="powered by"%> <a 
href="http://hww3.riverweb.com/space/pike/FinScribe">FinScribe</a></div>

<script src="/static/javascripts/dojo.js"></script>
<script type='text/javascript'>
    
dojo.hostenv.setModulePrefix("fins",
                                "/static/javascripts/fins"
);

dojo.require("dojo.widget.*");
dojo.require("fins.widget.*");
dojo.require("fins.widget.ComboPicker");    
//dojo.widget.getParser().createComponents(document);
</script>
<script src="/static/javascripts/menulayer.js" type="text/javascript"></script>
<script src="/static/javascripts/rounded-corners.js" type="text/javascript"></script>
<script src="/static/javascripts/bootstrap.js" type="text/javascript"></script>
<script type="text/javascript">
<% list_retrieve var="$jsfooter" %>
make_corners();
</script>
</body>
</html>


