<!-- this is 2header.phtml -->
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>general.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>wiki.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>snip.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>page.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>style.css"/>
   <link rel="STYLESHEET" type="text/css" href="/static/lightbox.css"/>
   <script src="<% theme show="path"%>functions.js"></script>
	<div style="display:none" id="object"><%$obj%></div>
