<!-- this is default adminfooter.phtml -->
         </div>
      </div>
      </div>
      </div>

</div>

<div id="page-bottom"><a href="/space/contact info"><%LOCALE id="1" string="contact info"%></a> | <%LOCALE id="2" string="powered by"%> <a 
href="http://hww3.riverweb.com/space/pike/FinScribe">FinScribe</a></div>

<xscript src="/static/javascripts/dojo/dojo.js" type="text/javascript"></xscript>
<script src="http://ajax.googleapis.com/ajax/libs/dojo/1.6.1/dojo/dojo.xd.js" type="text/javascript"></script>
<<script type='text/javascript'>
    
dojo.registerModulePath("fins",
                                 "<%syspref var="site.url"%>/static/javascripts/fins"
);

</script>
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/dojo/1.6/dijit/themes/tundra/tundra.css"
       />
<script src="/static/javascripts/menulayer.js" type="text/javascript"></script>
<script src="/static/javascripts/bootstrap.js" type="text/javascript"></script>
<script type="text/javascript">
<% list_retrieve var="$jsfooter" %>
</script>
</body>
</html>


