<!-- this is footer.phtml -->
         </div>
      </div>
      </div>
      </div>
         <div id="page-portlet-1-wrapper">
          <div id="page-portlet-1">
         <% snip snip="themes/default/portlet-1" %>
         </div>
         </div>

</div>

<div id="page-bottom"><a href="/space/contact info">contact info</a> | Powered by <a href="http://hww3.riverweb.com/space/pike/FinScribe">FinScribe</a></div>

<script src="/static/javascripts/dojo.js"></script>
<script type='text/javascript'>
    
dojo.hostenv.setModulePrefix("fins",
                                "/static/javascripts/fins"
);
    
</script>
<script src="/static/javascripts/menulayer.js" type="text/javascript"></script>
<script src="/static/javascripts/rounded-corners.js" type="text/javascript"></script>
<script src="/static/javascripts/bootstrap.js" type="text/javascript"></script>
<script type="text/javascript">
<% list_retrieve var="$jsfooter" %>
</script>
</body>
</html>


