<!-- this is footer.phtml -->
         </div>
      </div>
      </div>
      </div>
         <div id="page-portlet-1-wrapper">
          <div id="page-portlet-1">
         <% snip snip="themes/default/portlet-1" %>
         </div>
         </div>

</div>

<div id="page-bottom"><a href="/space/contact info"><%LOCALE id="1" string="contact info"%></a> | <%LOCALE id="2" string="powered by"%> <a 
href="http://bill.welliver.org/space/pike/FinScribe">FinScribe</a></div>

<script src="http://ajax.googleapis.com/ajax/libs/dojo/1.6.1/dojo/dojo.xd.js" type="text/javascript"></script>
<script type='text/javascript'>
    
dojo.registerModulePath("fins",
                                 "<%syspref var="site.url"%>/static/javascripts/fins"
);
    
</script>
<script src="/static/javascripts/menulayer.js" type="text/javascript"></script>
<script src="/static/javascripts/bootstrap.js" type="text/javascript"></script>
<script type="text/javascript">
// include code inserted previously in the parse process
<% list_retrieve var="$jsfooter" %>
</script>
</body>
</html>


