<!-- this is footer.phtml -->
         </div>
      </div>
      </div>
      </div>
         <div id="page-portlet-1-wrapper">
          <div id="page-portlet-1">
         <% snip snip="themes/default/portlet-1" %>
         </div>
         </div>

</div>

<div id="page-bottom"><a href="<%syspref var="site.url"%>/space/contact info"><%LOCALE id="1" string="contact info"%></a> | <%LOCALE id="2" string="powered by"%> <a 
href="http://bill.welliver.org/space/pike/FinScribe">FinScribe</a></div>
<%if data->config->config_name == "dev" %>
	<script src="<%syspref var="site.url"%>/static/javascripts/dojo/dojo.js" type="text/javascript"></script>
<% else %>
	<script src="http://ajax.googleapis.com/ajax/libs/dojo/1.6.1/dojo/dojo.xd.js" type="text/javascript"></script>
<% endif %>
<script type='text/javascript'>  
<%if data->config->config_name == "dev" %>
dojo.registerModulePath("fins", "<%syspref var="site.url"%>/static/javascripts/fins");
<% else %>
dojo.registerModulePath("fins", "<%syspref var="site.url"%>/static/javascripts/fins_release");
<% endif %>
</script>
<script src="/static/javascripts/menulayer.js" type="text/javascript"></script>
<script src="/static/javascripts/bootstrap.js" type="text/javascript"></script>
<script type="text/javascript" src="http://api.recaptcha.net/js/recaptcha_ajax.js"></script>
<script type="text/javascript">
// include code inserted previously in the parse process
dojo.require("dijit.Dialog");
dojo.require("fins.widget.Comments");
dojo.require("fins.widget.Recaptcha");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.TooltipDialog");
dojo.require("dojox.form.Uploader");
dojo.require("dojox.form.uploader.FileList");
dojo.require("dijit.Menu");
dojo.require("dijit.MenuItem");
dojo.require("dijit.Tree");
dojo.require("dojo.store.JsonRest");

//dojo.require("dojox.form.uploader.plugins.IFrame");
dojo.require("dojox.form.uploader.plugins.Flash");
<% list_retrieve var="$jsfooter" %>
</script>
</body>
</html>


