<!-- this is header.phtml -->
   <link rel="STYLESHEET" type="text/css" href="/space/themes/default/default.css"/>
   <!-- IE doesn't like XHTML markup for an empty script container :/ -->
   <script src="/space/themes/default/functions.js"></script>
  <xscript src="/static/javascripts/dojo.js"></script>
<script type='text/javascript'>
  djConfig = {
    // your local src/ directory is located at domain.com/path/to/local/dojo-0.2.2-ajax/src/
    baseScriptUri: '/static/javascripts/'
  };
</script>
<script type='text/javascript'
    src='http://o.aolcdn.com/iamalpha/.resource/jssdk/dojo-0.2.2/dojo.js'></script>
<script type='text/javascript'>
  // pull in the storage APIs
</script>


