<!-- this is 2header.phtml -->
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>general.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>wiki.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>snip.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>page.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>style.css"/>
   <link rel="STYLESHEET" type="text/css" href="<%syspref var="site.url"%>/static/lightbox.css"/>
   <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/dojo/1.6/dijit/themes/tundra/tundra.css"/>
   <link rel="STYLESHEET" type="text/css" href="<%syspref var="site.url"%>/static/javascripts/fins/widget/templates/Comments.css"/>
   <!-- IE doesn't like XHTML markup for an empty script container :/ -->
<script src="<% theme show="path"%>functions.js"></script>

<script type='text/javascript'>
  djConfig = {
    isDebug : false,
    disableFlashStorage : true,
<% if data->config->config_name == "dev" %>
    useXDomain: false,
<% else $%>
	useXDomain: false,
<% endif %>
  };

</script>

<% if data->config->config_name == "dev" %>
<script src="http://ajax.googleapis.com/ajax/libs/dojo/1.6.1/dojo/dojo.xd.js" type="text/javascript"></script>
<% else $%>
<script src="http://ajax.googleapis.com/ajax/libs/dojo/1.6.1/dojo/dojo.js" type="text/javascript"></script>
<% endif %>
<script type='text/javascript'>
<% if data->config->config_name == "dev" %>
	dojo.registerModulePath("fins", "<%syspref var="site.url"%>/static/javascripts/fins");	
<% else $%>
	dojo.registerModulePath("fins", "<%syspref var="site.url"%>/static/javascripts/fins_release");	
<% endif %>
</script>
<script src="<%syspref var="site.url"%>/static/javascripts/menulayer.js" type="text/javascript"></script>
<script src="<%syspref var="site.url"%>/static/javascripts/bootstrap.js" type="text/javascript"></script>
<div style="display:none" id="object"><%$obj%></div>