<!-- this is footer.phtml -->
         </div>
      </div>
      </div>
      </div>
         <div id="page-portlet-1-wrapper">
          <div id="page-portlet-1">
         <% snip snip="themes/default/portlet-1" %>
         </div>
         </div>

</div>

<div id="page-bottom"><a href="<%syspref var="site.url"%>/space/contact info"><%LOCALE id="1" string="contact info"%></a> | <%LOCALE id="2" string="powered by"%> <a 
href="http://bill.welliver.org/space/pike/FinScribe">FinScribe</a></div>
