
<!-- this is tagline.phtml -->
  <div id="page-logo">
    <img src="<% syspref var="site.logo" %>" alt="<%syspref var="site.name"%>" border="0"/>   
  </div>
  <div id="page-title">
   <div id="page-tagline"><%syspref var="site.tagline"%></div>
  <div id="page-buttons"> [
<% if data["obj"]=="start" %>
 start
<% else %>
<a href="/space/start">start</a>
<% endif %>
|
<% if data["obj"]=="object-index" %>
 index 
<% else %>
<a href="/space/object-index">index</a>
<% endif %>


<% if data["user"] %>
| logged in as <%$UserName%> | <a href="/exec/logout">logout</a>
<% if data["object_is_weblog"] %>
      |  <a href="#" onclick="openPostBlog('<%$obj%>'); return false;">post blog</a>
<!--      |  <a href="/exec/post/<%$obj%>">post blog</a> -->
  <% endif %>
  <% if data["is_admin"]==1 %> 
      | <a href="/admin/">admin</a>
   <% endif %>
   <% else %>
<!--
| <a href="/exec/login">login</a> 
-->
| <a href="#" onclick="openLogin()">login</a>
<% endif %>

]
<p/>
  <% breadcrumbs var="obj" %>
 </div>
