
<!-- this is tagline.phtml -->
  <div id="page-logo">
    <img src="<% syspref var="site.logo" %>" alt="<%syspref var="site.name"%>" border="0"/>   
  </div>
  <div id="page-title">
   <div id="page-tagline"><%syspref var="site.tagline"%></div>
  <div id="page-buttons"> [
<% if data["obj"]=="start" %>
 start
<% else %>
<%action_link controller="/space"%>start</a>
<% endif %>
|
<% if data["obj"]=="object-index" %>
 index 
<% else %>
<%action_link controller="/space" args="object-index"%>index</a>
<% endif %>






<% if data["user_object"] %>
| <%LOCALE id="3" string="logged in as"%> <%$user_object.username%> |
<%action_link controller="/exec" action="logout"%>logout</a> <br/> |
<%action_link controller="/account"%>my account</a> 
<% if data["object_is_weblog"] %>
      | 
<a href="<%action_url controller="/exec" action="post" args="$blog_source"%>" id="PostBlog">post blog</a> <br/>
  <% endif %>
  <% if data["is_admin"]==1 %> 
|
<%action_link controller="/admin"%>admin</a>
   <% endif %>
   <% else %>
|
<a href="<%action_url controller="/exec" action="login"%>" id="Login">login</a> 
<% endif %>

]
<p/>
<% if !data["in_admin"] %>
  <% breadcrumbs var="$obj" %>
<% else %>
<%action_link controller="/admin"%>admin</a>
<% endif %>
 </div>
</div>
