
<!-- this is tagline.phtml -->
  <div id="page-logo">
    <img src="<% syspref var="site.logo" %>" alt="<%syspref var="site.name"%>" border="0"/>   
  </div>
  <div id="page-title">
   <div id="page-tagline"><%syspref var="site.tagline"%></div>
  <div id="page-buttons"> [
<% if data["obj"]=="start" %>
 start
<% else %>
<a href="/space/start">start</a>
<% endif %>
|
<% if data["obj"]=="object-index" %>
 index 
<% else %>
<a href="/space/object-index">index</a>
<% endif %>


<% if data["user_object"] %>
| <%LOCALE id="3" string="logged in as"%> <%$user_object.UserName%> | <a href="/exec/logout"><%LOCALE id="4" string="logout"%></a>
<% if data["object_is_weblog"] %>
      |  <a href="/exec/post/<%$obj%>" id="PostBlog"><%LOCALE id="5" string="post blog"%></a>
  <% endif %>
  <% if data["is_admin"]==1 %> 
      | <a href="/admin/">admin</a>
   <% endif %>
   <% else %>
| <a href="/exec/login" id="Login"><%LOCALE id="6" string="login"%></a> 
<% endif %>

]
<p/>
<% if !data["in_admin"] %>
  <% breadcrumbs var="$obj" %>
<% else %>
  <a href="/admin"><%LOCALE id="7" string="admin"%></a>
<% endif %>
 </div>
</div>
