<%LOCALE id="171" string="Preferences:"%>
<b>
<% implode var="$startswith" splice="</b> &gt; <b>" final="</b> &gt; <b>"%>
</b>
<p>
<table>
<% foreach var="$preferences" val="pref" %>
<tr>
<td>
<%$pref.shortname %>: 
</td>
<td>
<% if data->pref["type"] == FinScribe.BOOLEAN %>
<div dojoType="fins:InlineBooleanBox" 
id="<%$pref.name%>" name="<%$pref.shortname%>">
<%$pref.booleanvalue%>
</div>
<%else %>
<div dojoType="dojo:InlineEditBox" id="<%$pref.name%>" 
name="<%$pref.name%>">
<%$pref.value%>
</div>
<% endif %>
</td>
</tr>
<% end %>
</table>
<p><i><%LOCALE id="172" string="Click on a value to edit it."%></i>
</p>
