<html>
<head>
   <link rel="STYLESHEET" type="text/css" href="/space/themes/default/default.css" />
   <title><%syspref var="site.name" %> :: <%$obj%></title>
</head>
<body>
<%@include file="tagline.phtml" %>

   <div id="page-wrapper">
    <div id="page-content">

   <h3><%$obj%></h3>
   Created by <%$author_username%>. Last updated by <%$editor_username%>, 
<%$when%>. 
Version #<%$version%>.
   <br/>
   
   
   <font color="red"><% flash var="msg" %></font>
   <p/>
   
   <div class="snip-wrapper">
      <div class="snip-content">
         <div>
         <%$content%>
         
         <p/>
         <b><%$numcomments%> Comments</b> | <a href="/exec/comments/<%$obj%>">Post a Comment</a> 
         | <a href="/rss/<%$obj%>?type=comments">RSS Feed</a>

         <p/>
<%$comments%>
         </div>
      </div>
      </div>
      </div>
         <div id="page-portlet-1-wrapper">
          <div id="page-portlet-1">
         <%snip snip="themes/default/portlet-1"%>
         </div>
         </div>
         
</div>

<div id="page-bottom"><a href="/space/contact+info">contact info</a> | Copyright 1995-2005 Bill Welliver</div>
</body>
</html>

