  <%@ include file="top.phtml" %>
  <%@ include file="header.phtml" %>
   <title><%syspref var="site.name" %> :: <%$title %></title>
   <%$heads %>
<%@include file="pagebegin.phtml"%>


   <h3><%$obj%></h3>
   <%LOCALE id="103" string="Created by"%> <%$author_username%>. <%LOCALE id="8" string="Last updated by"%> 
<%$editor_username%>, 
<%$when%>. 
<%LOCALE id="9" string="Version #"%><%$version%>.
   <br/>
   
   
   <font color="red"><% flash %></font>
   <p/>
   
   <div class="snip-wrapper">
      <div class="snip-content">
         <div>
	 <%render content="$content" object="$object"%>         
         <p/>
         <b><%$numcomments%> <%LOCALE id="10" string="Comments"%></b> | <a 
href="/exec/comments/<%$obj%>"><%LOCALE id="11" string="Post a Comment"%></a> 
         | <a href="/rss/<%$obj%>?type=comments"><%LOCALE id="12" string="RSS Feed"%></a>

         <p/>
<%$comments%>
         </div>
      </div>
      </div>
      </div>
         <div id="page-portlet-1-wrapper">
          <div id="page-portlet-1">
         <%snip snip="themes/default/portlet-1"%>
         </div>
         </div>
         

  <%@ include file="pageend.phtml" %>
  <%@ include file="footer.phtml" %>
  <%@ include file="bottom.phtml" %>

