  <%@ include file="top.phtml" %>
  <%@ include file="header.phtml" %>
   <title><%syspref var="site.name" %> :: <%$title %></title>
   <%$heads %>
<%@include file="pagebegin.phtml"%>


   <h3><%$obj%></h3>
   Created by <%$author_username%>. Last updated by <%$editor_username%>, 
<%$when%>. 
Version #<%$version%>.
   <br/>
   
   
   <font color="red"><% flash %></font>
   <p/>
   
   <div class="snip-wrapper">
      <div class="snip-content">
         <div>
	 <%render content="$content" object="$object"%>         
         <p/>
         <b><%$numcomments%> Comments</b> | <a href="/exec/comments/<%$obj%>">Post a Comment</a> 
         | <a href="/rss/<%$obj%>?type=comments">RSS Feed</a>

         <p/>
<%$comments%>
         </div>
      </div>
      </div>
      </div>
         <div id="page-portlet-1-wrapper">
          <div id="page-portlet-1">
         <%snip snip="themes/default/portlet-1"%>
         </div>
         </div>
         

<%@ include file="footer.phtml" %>

</div>
  <%@ include file="bottom.phtml" %>

